'use client';
import {useMemo,useState} from 'react';
import {Card,Badge} from '@lotediretor/ui';
import {getJson,postJson,State,uploadFile,useApi} from './ApiBox';
import {AiChatBox} from './AiChatBox';

type AnyMap=Record<string,any>;
export function CondoWorkspace(){
  const {data,error,loading,reload}=useApi<any>('/api/v1/condominiums');
  const [selected,setSelected]=useState('');const [baseDate,setBaseDate]=useState(new Date().toISOString().slice(0,10));
  const [dashboard,setDashboard]=useState<any>(null),[rules,setRules]=useState<any>(null),[evidence,setEvidence]=useState<any>(null),[units,setUnits]=useState<any>(null),[areas,setAreas]=useState<any>(null),[works,setWorks]=useState<any>(null),[assemblies,setAssemblies]=useState<any>(null),[maintenance,setMaintenance]=useState<any>(null),[occurrences,setOccurrences]=useState<any>(null),[compliance,setCompliance]=useState<any>(null);
  const [query,setQuery]=useState(''),[uploadStatus,setUploadStatus]=useState(''),[newName,setNewName]=useState('Condomínio exemplo');
  const [unitCode,setUnitCode]=useState('101'),[areaName,setAreaName]=useState('Cobertura'),[workTitle,setWorkTitle]=useState('Reforma da unidade'),[meetingTitle,setMeetingTitle]=useState('Assembleia ordinária');
  const current=useMemo(()=>data?.items?.find((x:any)=>x.id===selected),[data,selected]);
  async function createCondo(){const x:any=await postJson('/api/v1/condominiums',{name:newName,kind:'VERTICAL'});await reload();await select(x.id)}
  async function select(id:string){setSelected(id);const [d,r,u,a,w,m,mt,o,c]=await Promise.all([getJson(`/api/v1/condominiums/${id}/dashboard?baseDate=${baseDate}`),getJson(`/api/v1/condominiums/${id}/rules?baseDate=${baseDate}`),getJson(`/api/v1/condominiums/${id}/units`),getJson(`/api/v1/condominiums/${id}/common-areas`),getJson(`/api/v1/condominiums/${id}/works`),getJson(`/api/v1/condominiums/${id}/assemblies`),getJson(`/api/v1/condominiums/${id}/maintenance`),getJson(`/api/v1/condominiums/${id}/occurrences`),getJson(`/api/v1/condominiums/${id}/compliance`)]);setDashboard(d);setRules(r);setUnits(u);setAreas(a);setWorks(w);setAssemblies(m);setMaintenance(mt);setOccurrences(o);setCompliance(c)}
  async function search(){if(!selected)return;setEvidence(await getJson(`/api/v1/condominiums/${selected}/evidence?q=${encodeURIComponent(query)}`));}
  async function review(ruleId:string,decision:'CONFIRMED'|'REJECTED'){await postJson(`/api/v1/condominiums/${selected}/rules/${ruleId}/review`,{decision,validFrom:`${baseDate}T00:00:00Z`});await select(selected)}
  async function upload(file?:File){if(!file||!selected)return;setUploadStatus('Enviando…');try{const stored=await uploadFile<any>(file);await postJson(`/api/v1/condominiums/${selected}/documents`,{fileId:stored.id,title:file.name,kind:'OTHER'});setUploadStatus('Documento registrado. OCR/indexação e regras CANDIDATE serão processados pelo worker.');await select(selected)}catch(e:any){setUploadStatus(`Erro: ${e.message}`)}}
  async function addUnit(){if(!selected)return;await postJson(`/api/v1/condominiums/${selected}/units`,{code:unitCode,kind:'UNIT'});await select(selected)}
  async function addArea(){if(!selected)return;await postJson(`/api/v1/condominiums/${selected}/common-areas`,{code:`AREA-${Date.now()}`,name:areaName,kind:'COMMON'});await select(selected)}
  async function addWork(){if(!selected||!units?.items?.[0])return;await postJson(`/api/v1/condominiums/${selected}/works`,{unitId:units.items[0].id,title:workTitle,workType:'REFORM'});await select(selected)}
  async function addAssembly(){if(!selected)return;await postJson(`/api/v1/condominiums/${selected}/assemblies`,{title:meetingTitle,scheduledAt:new Date(Date.now()+7*86400000).toISOString(),quorumRule:{minFraction:0.5,minPresent:1}});await select(selected)}
  async function addMaintenance(){if(!selected)return;await postJson(`/api/v1/condominiums/${selected}/maintenance`,{systemCode:'FIRE',title:'Inspeção preventiva',intervalDays:365,nextDueAt:new Date(Date.now()+30*86400000).toISOString().slice(0,10)});await select(selected)}
  async function addOccurrence(){if(!selected)return;await postJson(`/api/v1/condominiums/${selected}/occurrences`,{category:'GENERAL',title:'Ocorrência para revisão humana',severity:'LOW'});await select(selected)}
  async function makeReport(){if(!selected)return;const r=await postJson(`/api/v1/condominiums/${selected}/report`,{baseDate},{idempotent:true});alert(`Relatório enfileirado: ${r.id}`)}
  const k=(key:string)=>dashboard?.counters?.[key]??0;
  return <>
    <header className="pageHead"><div><h1>Condomínio 360</h1><p>Documentos privados, regras temporais, unidades, obras, assembleias, manutenção, ocorrências e compliance.</p></div><Badge tone="success">v19-rc2 · workflow operacional</Badge></header>
    <State loading={loading} error={error}/>
    <div className="twoCol"><Card className="panel noTop"><h2>Condomínios</h2><div className="inlineForm"><input value={newName} onChange={e=>setNewName(e.target.value)}/><button onClick={()=>void createCondo()}>Criar</button></div><label>Data-base<input type="date" value={baseDate} onChange={e=>setBaseDate(e.target.value)}/></label>{data?.items?.length?<div className="listButtons">{data.items.map((x:any)=><button className={selected===x.id?'activeChoice':'secondary'} key={x.id} onClick={()=>void select(x.id)}><b>{x.name}</b><span>{x.documents} docs · {x.confirmed_rules} regras</span></button>)}</div>:!loading&&<div className="notice neutral">Nenhum condomínio cadastrado.</div>}{dashboard&&<div className="metricGrid">{[['units','Unidades'],['commonAreas','Áreas comuns'],['openWorks','Obras abertas'],['upcomingAssemblies','Assembleias'],['maintenanceDue','Manut. 30d'],['openOccurrences','Ocorrências'],['pendingCompliance','Compliance'],['confirmedRules','Regras']].map(([a,b])=><div className="metric" key={a}><b>{k(a)}</b><span>{b}</span></div>)}</div>}<label>Documento<input type="file" accept=".pdf,.txt,.md" disabled={!selected} onChange={e=>void upload(e.target.files?.[0])}/></label>{uploadStatus&&<div className="notice neutral">{uploadStatus}</div>}<div className="inlineForm"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="fachada, obra, garagem…"/><button disabled={!selected} onClick={()=>void search()}>Buscar evidência</button></div>{evidence&&<pre>{JSON.stringify(evidence,null,2)}</pre>}<button disabled={!selected} onClick={()=>void makeReport()}>Gerar Condomínio 360</button></Card>
    <Card className="panel noTop"><h2>Regras na data-base</h2>{rules?.items?.length?<div className="ruleList">{rules.items.map((r:any)=><article key={r.id}><div><b>{r.title}</b><Badge tone={r.status==='CONFIRMED'?'success':'warning'}>{r.status}</Badge></div><p>{r.rule_text}</p><small>{r.source_locator||'sem localizador'} · {r.extraction_method||'manual'}</small>{r.status==='CANDIDATE'&&<div className="inlineForm"><button onClick={()=>void review(r.id,'CONFIRMED')}>Confirmar</button><button className="secondary" onClick={()=>void review(r.id,'REJECTED')}>Rejeitar</button></div>}</article>)}</div>:<div className="notice neutral">Somente regras existentes e vigentes aparecem aqui.</div>}</Card></div>
    {selected&&<div className="threeCol"><Card className="panel"><h2>Unidades e áreas</h2><div className="inlineForm"><input value={unitCode} onChange={e=>setUnitCode(e.target.value)}/><button onClick={()=>void addUnit()}>Adicionar unidade</button></div><div className="inlineForm"><input value={areaName} onChange={e=>setAreaName(e.target.value)}/><button onClick={()=>void addArea()}>Adicionar área comum</button></div><pre>{JSON.stringify({units:units?.items?.slice(0,20),areas:areas?.items?.slice(0,20)},null,2)}</pre></Card><Card className="panel"><h2>Obras e assembleias</h2><div className="inlineForm"><input value={workTitle} onChange={e=>setWorkTitle(e.target.value)}/><button disabled={!units?.items?.length} onClick={()=>void addWork()}>Solicitar obra</button></div><div className="inlineForm"><input value={meetingTitle} onChange={e=>setMeetingTitle(e.target.value)}/><button onClick={()=>void addAssembly()}>Criar assembleia</button></div><pre>{JSON.stringify({works:works?.items?.slice(0,10),assemblies:assemblies?.items?.slice(0,10)},null,2)}</pre></Card><Card className="panel"><h2>Operação e compliance</h2><div className="inlineForm"><button onClick={()=>void addMaintenance()}>Adicionar manutenção</button><button className="secondary" onClick={()=>void addOccurrence()}>Abrir ocorrência</button></div><pre>{JSON.stringify({maintenance:maintenance?.items?.slice(0,10),occurrences:occurrences?.items?.slice(0,10),compliance:compliance?.items?.slice(0,10)},null,2)}</pre></Card></div>}
    {rules&&<AiChatBox assistant="condominio" title="A.I Condomínio" subjectId={selected} baseDate={baseDate}/>}<small>{current?.name?`Workspace: ${current.name}`:''} A IA não aplica sanções ou altera regras sem ação humana explícita.</small>
  </>;
}
