'use client';
import {useState} from 'react';
import {Card,Badge} from '@lotediretor/ui';
import {MapView} from '../MapView';
import {getJson,pollJson,postJson,useApi} from './ApiBox';
import {AiChatBox} from './AiChatBox';

export function Imovel360Workspace(){
  const [lat,setLat]=useState('-23.5505');const [lon,setLon]=useState('-46.6333');const [address,setAddress]=useState('');const [resolverMode,setResolverMode]=useState<'point'|'address'>('point');const [baseDate,setBaseDate]=useState(new Date().toISOString().slice(0,10));const [municipality,setMunicipality]=useState('3550308');const [area,setArea]=useState('80');const [result,setResult]=useState<any>(null);const [analysisRun,setAnalysisRun]=useState<any>(null);const [propertyId,setPropertyId]=useState('');const [note,setNote]=useState('');const [diligence,setDiligence]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');
  const coverage=useApi<any>(`/api/v1/municipalities/${municipality}/coverage`);const developments=useApi<any>('/api/v1/property360/developments');const leads=useApi<any>('/api/v1/property360/crm/leads');const market=useApi<any>(`/api/v1/property360/market/snapshots?municipality=${municipality}`);const properties=useApi<any>('/api/v1/property360/properties?limit=100');
  const [developmentName,setDevelopmentName]=useState('Novo empreendimento');const [leadName,setLeadName]=useState('Nova oportunidade');
  async function action(type:string){setBusy(type);setError('');try{
    if(type==='resolve'){const payload=resolverMode==='address'?{address,municipalityIbge:municipality,baseDate}:{point:{lat:Number(lat),lon:Number(lon)},baseDate};const x:any=await postJson('/api/v1/parcel/resolve',payload);setResult({kind:'Parcel Resolver v20',data:x});if(x?.selected?.municipality_ibge)setMunicipality(x.selected.municipality_ibge);}
    if(type==='analysis'){const payload=resolverMode==='address'?{address,municipalityIbge:municipality,baseDate}:{point:{lat:Number(lat),lon:Number(lon)},baseDate};const a:any=await postJson('/api/v1/analysis',payload,{idempotent:true});setAnalysisRun(a);setResult({kind:'Análise territorial congelável',data:a});}
    if(type==='comparables'){setResult({kind:'Comparáveis',data:await getJson(`/api/v1/property360/comparables?municipality=${municipality}&propertyType=APARTMENT`)});}
    if(type==='avm'){setResult({kind:'AVM',data:await postJson('/api/v1/property360/avm',{municipality,propertyType:'APARTMENT',areaM2:Number(area),propertyId:propertyId||undefined},{idempotent:true})});}
  }catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function saveProperty(){if(!analysisRun?.run?.id)return;setBusy('save-property');setError('');try{const p:any=await postJson('/api/v1/property360/properties/from-analysis',{analysisRunId:analysisRun.run.id,name:`Imóvel ${municipality}`,address:resolverMode==='address'?address:undefined,tags:['analisado']});setPropertyId(p.property.id);await properties.reload();setResult({kind:'Ficha 360 criada',data:p});}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function loadFicha(id=propertyId){if(!id)return;setBusy('ficha');setError('');try{setPropertyId(id);setResult({kind:'Ficha 360',data:await getJson(`/api/v1/property360/properties/${id}/ficha`)});}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function createReport(){
    if(!analysisRun?.run?.id)return;setBusy('report');setError('');
    try{
      const queued:any=await postJson('/api/v1/reports',{kind:'PROPERTY360',subjectType:'analysis',subjectId:analysisRun.run.id,templateCode:'PROPERTY360_360',baseDate},{idempotent:true});
      setResult({kind:'Relatório 360 enfileirado',data:queued});
      const completed:any=await pollJson(`/api/v1/reports/${queued.id}/status`,(value:any)=>['COMPLETED','FAILED'].includes(String(value?.status||'')),90000,1000);
      if(completed.status!=='COMPLETED')throw new Error(`Relatório ${completed.status}: ${completed.error||'falha sem detalhe'}`);
      const manifest=await getJson(`/api/v1/reports/${queued.id}/manifest`);setResult({kind:'Relatório 360 · manifesto e evidências',data:manifest});
    }catch(e:any){setError(e.message)}finally{setBusy('')}
  }
  async function addNote(){if(!propertyId||!note.trim())return;await postJson(`/api/v1/property360/properties/${propertyId}/notes`,{body:note,tags:['workspace']});setNote('');await loadFicha(propertyId);}
  async function addDiligence(){if(!propertyId||!diligence.trim())return;await postJson('/api/v1/property360/diligences',{propertyId,title:diligence,priority:'MEDIUM'});setDiligence('');await loadFicha(propertyId);}
  async function createDevelopment(){await postJson('/api/v1/property360/developments',{name:developmentName,municipality,status:'PROSPECT'});await developments.reload();}
  async function createLead(){await postJson('/api/v1/property360/crm/leads',{name:leadName,stage:'NEW',score:10,tags:['manual'],propertyId:propertyId||undefined});await leads.reload();}
  return <>
    <header className="pageHead"><div><h1>Imóvel 360 · Explorer e Ficha 360</h1><p>Território, análise temporal, imóvel persistido, mercado, CRM, diligências e Relatório 360 congelado.</p></div><Badge tone="success">v20 · analysis/report</Badge></header>
    <div className="workspace2"><Card className="sidePanel"><b>Consulta territorial</b><label>Entrada<select aria-label="Modo de resolução" value={resolverMode} onChange={e=>setResolverMode(e.target.value as any)}><option value="point">Coordenada</option><option value="address">Endereço indexado</option></select></label>{resolverMode==='address'?<label>Endereço<input aria-label="Endereço" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Endereço completo"/></label>:<><label>Latitude<input aria-label="Latitude" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>Longitude<input aria-label="Longitude" value={lon} onChange={e=>setLon(e.target.value)}/></label></>}<label>Data-base<input aria-label="Data-base" type="date" value={baseDate} onChange={e=>setBaseDate(e.target.value)}/></label><button onClick={()=>void action('resolve')} disabled={!!busy}>Resolver parcela</button><button className="secondary" onClick={()=>void action('analysis')} disabled={!!busy}>Analisar</button><button className="secondary" onClick={()=>void saveProperty()} disabled={!!busy||!analysisRun?.run?.id}>Salvar como Ficha 360</button><button className="secondary" onClick={()=>void createReport()} disabled={!!busy||!analysisRun?.run?.id}>{busy==='report'?'Gerando…':'Gerar Relatório 360'}</button><hr/><b>Fichas salvas</b><select value={propertyId} onChange={e=>{setPropertyId(e.target.value);if(e.target.value)void loadFicha(e.target.value)}}><option value="">Selecione</option>{properties.data?.items?.map((p:any)=><option key={p.id} value={p.id}>{p.name||p.id.slice(0,8)} · {p.municipality_ibge||'—'}</option>)}</select><hr/><b>Mercado / AVM</b><label>Município IBGE<input value={municipality} onChange={e=>setMunicipality(e.target.value)}/></label><label>Área (m²)<input value={area} onChange={e=>setArea(e.target.value)}/></label><button className="secondary" onClick={()=>void action('comparables')} disabled={!!busy}>Ver comparáveis</button><button className="secondary" onClick={()=>void action('avm')} disabled={!!busy}>Calcular AVM</button>{error&&<div className="notice error" role="alert">{error}</div>}</Card>
      <div><div className="mapWrap compact"><MapView/></div><Card className="resultPanel"><div className="resultTitle"><b data-testid="imovel-result-kind">{result?.kind||'Resultado técnico'}</b>{busy&&<span>processando…</span>}</div>{result?<pre data-testid="imovel-result-json">{JSON.stringify(result.data,null,2)}</pre>:<div className="notice neutral">Sem parcela/zona/regra confirmada, a plataforma retorna insuficiência de dados em vez de inferir.</div>}</Card>{analysisRun&&<AiChatBox assistant="cidades" title="A.I Cidades" municipality={analysisRun?.resolver?.selected?.municipality_ibge} zoneCode={analysisRun?.zone?.code} baseDate={baseDate}/>}</div>
    </div>
    {propertyId&&<div className="twoCol"><Card className="panel"><h2>Notas da Ficha 360</h2><div className="inlineForm"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota técnica/comercial"/><button onClick={()=>void addNote()}>Adicionar</button></div></Card><Card className="panel"><h2>Diligências</h2><div className="inlineForm"><input value={diligence} onChange={e=>setDiligence(e.target.value)} placeholder="Pendência a verificar"/><button onClick={()=>void addDiligence()}>Criar</button></div></Card></div>}
    <div className="twoCol"><Card className="panel"><h2>Empreendimentos</h2><div className="inlineForm"><input value={developmentName} onChange={e=>setDevelopmentName(e.target.value)}/><button onClick={()=>void createDevelopment()}>Criar</button></div>{developments.data?.items?.map((x:any)=><div className="itemRow" key={x.id}><b>{x.name}</b><span>{x.status} · {x.municipality_ibge||'sem município'}</span></div>)||<div className="notice neutral">Nenhum empreendimento.</div>}</Card><Card className="panel"><h2>CRM / Prospecção</h2><div className="inlineForm"><input value={leadName} onChange={e=>setLeadName(e.target.value)}/><button onClick={()=>void createLead()}>Criar lead</button></div>{leads.data?.items?.map((x:any)=><div className="itemRow" key={x.id}><b>{x.name}</b><span>{x.stage} · score {x.score}</span></div>)||<div className="notice neutral">Nenhum lead.</div>}</Card></div>
    <Card className="panel"><h2>Cobertura territorial</h2>{coverage.data?<pre>{JSON.stringify(coverage.data,null,2)}</pre>:<div className="notice neutral">Sem catálogo de cobertura carregado.</div>}</Card><Card className="panel"><h2>Mercado versionado</h2>{market.data?.items?.length?<pre>{JSON.stringify(market.data.items,null,2)}</pre>:<div className="notice neutral">Nenhum market snapshot real publicado para este município. Comparáveis DEMO permanecem explicitamente DEMO.</div>}</Card>
  </>;
}
