'use client';
import {useState} from 'react';import {Card,Badge} from '@lotediretor/ui';import {getJson,postJson,State,useApi} from './ApiBox';
export function RuralWorkspace(){const {data,error,loading,reload}=useApi<any>('/api/v1/rural/assets');const layers=useApi<any>('/api/v1/rural/layers');const [selected,setSelected]=useState('');const [detail,setDetail]=useState<any>(null);const [graph,setGraph]=useState<any>(null);const [search,setSearch]=useState<any>(null);const [out,setOut]=useState<any>(null);const [busy,setBusy]=useState(false);const [name,setName]=useState('Imóvel rural');const [q,setQ]=useState('');
async function createAsset(){const geometry={type:'MultiPolygon',coordinates:[[[[-46.65,-23.56],[-46.64,-23.56],[-46.64,-23.55],[-46.65,-23.55],[-46.65,-23.56]]]]};await postJson('/api/v1/rural/assets',{name,municipality:'3550308',geometry});await reload()}
async function choose(id:string){setSelected(id);setDetail(await getJson(`/api/v1/rural/assets/${id}/detail`));setGraph(await getJson(`/api/v1/rural/assets/${id}/identity-graph`))}
async function monitor(){if(!selected)return;const m:any=await postJson(`/api/v1/rural/assets/${selected}/monitors`,{monitorType:'SOURCE_CHANGE'});setOut(m);await choose(selected)}
async function checkMonitor(id:string){setOut(await postJson(`/api/v1/rural/assets/${selected}/monitors/${id}/check`,{}, {idempotent:true}));await choose(selected)}
async function recalc(){if(!selected)return;setBusy(true);try{setOut(await postJson(`/api/v1/rural/assets/${selected}/overlaps/recalculate`,{}, {idempotent:true}));await choose(selected)}catch(e:any){setOut({error:e.message})}finally{setBusy(false)}}
async function rebuild(){if(!selected)return;setGraph(await postJson(`/api/v1/rural/assets/${selected}/identity-graph/rebuild`,{}, {idempotent:true}));setGraph(await getJson(`/api/v1/rural/assets/${selected}/identity-graph`))}
async function doSearch(){setSearch(await getJson(`/api/v1/rural/search?q=${encodeURIComponent(q)}`))}
async function exportAsset(format:'KML'|'KMZ'){if(!selected)return;setOut(await postJson(`/api/v1/rural/assets/${selected}/exports`,{format},{idempotent:true}))}
async function report(){if(!selected)return;setOut(await postJson(`/api/v1/rural/assets/${selected}/report`,{},{idempotent:true}))}
return <><header className="pageHead"><div><h1>RE Rural 360</h1><p>CAR, SNCR/CCIR, SIGEF, CIB, embargos, PRODES e crédito rural preservando origem, vigência e natureza jurídica.</p></div><Badge tone="success">v19-rc2 · identity graph</Badge></header><State loading={loading} error={error}/>
<Card className="panel"><h2>Busca rural unificada</h2><div className="inlineForm"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="código CAR/SNCR/SIGEF/CIB, identificador ou texto"/><button onClick={()=>void doSearch()}>Buscar</button></div>{search&&<pre>{JSON.stringify(search,null,2)}</pre>}<small>Campos sensíveis são ocultados por padrão. Busca não transforma cadastro em prova de domínio.</small></Card>
<div className="twoCol"><Card className="panel noTop"><h2>Ativos</h2><div className="inlineForm"><input value={name} onChange={e=>setName(e.target.value)}/><button onClick={()=>void createAsset()}>Criar ativo de teste</button></div>{data?.items?.length?<table className="dataTable"><thead><tr><th>Ativo</th><th>Município</th><th>Área</th><th>Registros</th><th>Monitores</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.id} className={selected===x.id?'selectedRow':''} onClick={()=>void choose(x.id)}><td>{x.name||x.id}</td><td>{x.municipality_ibge||'—'}</td><td>{x.area_m2?`${Number(x.area_m2).toFixed(0)} m²`:'sem geometria'}</td><td>{x.registry_records}</td><td>{x.active_monitors}</td></tr>)}</tbody></table>:!loading&&<div className="notice neutral">Nenhum ativo rural cadastrado.</div>}<div className="inlineForm"><button disabled={!selected||busy} onClick={()=>void recalc()}>{busy?'Calculando…':'Recalcular overlaps'}</button><button className="secondary" disabled={!selected} onClick={()=>void rebuild()}>Recalcular identity graph</button><button className="secondary" disabled={!selected} onClick={()=>void monitor()}>Criar monitor</button></div><div className="inlineForm"><button className="secondary" disabled={!selected} onClick={()=>void exportAsset('KML')}>Exportar KML</button><button className="secondary" disabled={!selected} onClick={()=>void exportAsset('KMZ')}>Exportar KMZ</button><button disabled={!selected} onClick={()=>void report()}>Gerar Rural 360</button></div></Card>
<Card className="panel noTop"><h2>Detalhe / grafo</h2>{detail?<><pre>{JSON.stringify(detail,null,2)}</pre>{detail.monitors?.map((m:any)=><button className="secondary" key={m.id} onClick={()=>void checkMonitor(m.id)}>Checar {m.monitor_type}</button>)}</>:<div className="notice neutral">Selecione um ativo.</div>}{graph&&<><h3>Identity graph</h3><pre>{JSON.stringify(graph,null,2)}</pre></>}{out&&<><h3>Última operação</h3><pre>{JSON.stringify(out,null,2)}</pre></>}</Card></div>
<Card className="panel"><h2>Camadas de referência</h2>{layers.data?.items?.length?<table className="dataTable"><thead><tr><th>Camada</th><th>Autoridade</th><th>Natureza</th><th>Status</th><th>Features</th><th>Última ingestão</th></tr></thead><tbody>{layers.data.items.map((x:any)=><tr key={x.code}><td>{x.code} · {x.title}</td><td>{x.authority}</td><td>{x.legal_nature||'—'}</td><td>{x.status}</td><td>{x.features}</td><td>{x.last_ingested_at||'sem snapshot publicado'}</td></tr>)}</tbody></table>:<div className="notice neutral">Sem catálogo.</div>}<small>CONFIGURED não significa ingerido. Cada conclusão exige snapshot oficial validado, provenance e data-base.</small></Card></>}
