services:
  platform-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
  control-api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
  solar-engine:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
  aitec-engine:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
