services:
  platform-db:
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -h 127.0.0.1 -U ${PLATFORM_DB_MIGRATION_USER:-lotediretor} -d ${PLATFORM_DB_NAME:-lotediretor}
      start_period: 15s
  control-db:
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -h 127.0.0.1 -U ${CONTROL_DB_MIGRATION_USER:-lotediretor_control} -d ${CONTROL_DB_NAME:-lotediretor_control}
      start_period: 15s
  opensearch:
    environment:
      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      DISABLE_SECURITY_PLUGIN: 'true'
    healthcheck:
      test:
      - CMD-SHELL
      - "curl -fsS 'http://127.0.0.1:9200/_cluster/health?wait_for_status=yellow&timeout=5s' >/dev/null"
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s
