from __future__ import annotations
import os,time,requests,psycopg

from index_schema import embedding_fingerprint,index_mapping,index_meta,index_properties

DB=os.environ['PLATFORM_DATABASE_URL']
OPENSEARCH=os.getenv('OPENSEARCH_URL','').rstrip('/')
INDEX=os.getenv('OPENSEARCH_EVIDENCE_INDEX','lotediretor-evidence-v3')
INTERVAL=float(os.getenv('AI_INDEX_INTERVAL_SECONDS','2'))
EMBED_ENDPOINT=os.getenv('AI_EMBEDDINGS_ENDPOINT','').strip()
EMBED_MODEL=os.getenv('AI_EMBEDDINGS_MODEL','').strip()
EMBED_REVISION=os.getenv('AI_EMBEDDINGS_REVISION','').strip() or EMBED_MODEL
EMBED_KEY=os.getenv('AI_EMBEDDINGS_API_KEY',os.getenv('AI_API_KEY','')).strip()
EMBED_DIM=max(1,int(os.getenv('AI_EMBEDDINGS_DIMENSION','1536')))
OS_USER=os.getenv('OPENSEARCH_USERNAME','').strip();OS_PASSWORD=os.getenv('OPENSEARCH_PASSWORD','').strip()

# RC3 contracts remain explicit here even though the v20 mapping is generated by
# index_schema.py. These executable guards prevent a shared-schema refactor from
# silently relaxing the retained public/private/temporal/vector safety contract.
STRICT_DYNAMIC_MAPPING_CONTRACT={'dynamic':'strict'}
RC3_INDEX_FIELD_CONTRACT={
    'tenant_id':{'type':'keyword'},
    'document_version_id':{'type':'keyword'},
    'visibility':{'type':'keyword'},
    'knowledge_status':{'type':'keyword'},
    'retrieval_allowed':{'type':'boolean'},
    'municipality_ibge':{'type':'keyword'},
    'valid_from':{'type':'date'},
    'valid_to':{'type':'date'},
    'embedding':{'type':'knn_vector'},
}


def _auth(): return (OS_USER,OS_PASSWORD) if (OS_USER or OS_PASSWORD) else None

def _embedding_fingerprint():
    return embedding_fingerprint(EMBED_MODEL,EMBED_REVISION,EMBED_DIM) if EMBED_MODEL else None


def ensure_index():
    if not OPENSEARCH:return False
    mapping=index_mapping(EMBED_DIM,EMBED_MODEL,EMBED_REVISION)
    mappings=mapping.get('mappings') or {}
    if mappings.get('dynamic')!=STRICT_DYNAMIC_MAPPING_CONTRACT['dynamic']:
        raise RuntimeError('opensearch_mapping_must_remain_dynamic_strict')
    generated_properties=mappings.get('properties') or {}
    for field,expected in RC3_INDEX_FIELD_CONTRACT.items():
        actual=generated_properties.get(field) or {}
        if any(actual.get(key)!=value for key,value in expected.items()):
            raise RuntimeError(f'opensearch_rc3_field_contract_mismatch:{field}')
    head=requests.head(f'{OPENSEARCH}/{INDEX}',auth=_auth(),timeout=10)
    if head.status_code==404:
        r=requests.put(f'{OPENSEARCH}/{INDEX}',json=mapping,auth=_auth(),timeout=15);r.raise_for_status();return True
    if head.status_code>=400:head.raise_for_status()

    existing=requests.get(f'{OPENSEARCH}/{INDEX}/_mapping',auth=_auth(),timeout=15)
    existing.raise_for_status();raw=existing.json()
    descriptor=raw.get(INDEX) or next(iter(raw.values()),{})
    mappings=descriptor.get('mappings') or {}
    properties=mappings.get('properties') or {}
    existing_dimension=((properties.get('embedding') or {}).get('dimension'))
    if existing_dimension is not None and int(existing_dimension)!=EMBED_DIM:
        raise RuntimeError(f'opensearch_embedding_dimension_mismatch:{existing_dimension}:expected:{EMBED_DIM}:rebuild_required')

    expected_fingerprint=_embedding_fingerprint()
    current_fingerprint=(mappings.get('_meta') or {}).get('embedding_fingerprint')
    if expected_fingerprint and current_fingerprint!=expected_fingerprint:
        raise RuntimeError(
            f'opensearch_embedding_fingerprint_mismatch:{current_fingerprint or "missing"}:expected:{expected_fingerprint}:rebuild_required'
        )

    upgrade={'_meta':index_meta(EMBED_MODEL,EMBED_REVISION,EMBED_DIM),'properties':index_properties(EMBED_DIM)}
    r=requests.put(f'{OPENSEARCH}/{INDEX}/_mapping',json=upgrade,auth=_auth(),timeout=15)
    if r.status_code>=400:
        raise RuntimeError(f'opensearch_mapping_upgrade_rejected:{r.text[:1200]}')
    return True


def embed(text:str):
    if not (EMBED_ENDPOINT and EMBED_MODEL and EMBED_KEY):return None
    r=requests.post(EMBED_ENDPOINT,headers={'authorization':f'Bearer {EMBED_KEY}','content-type':'application/json'},json={'model':EMBED_MODEL,'input':text[:24000],'encoding_format':'float'},timeout=float(os.getenv('AI_EMBEDDINGS_TIMEOUT_SECONDS','20')))
    r.raise_for_status();raw=r.json();vec=((raw.get('data') or [{}])[0].get('embedding') if isinstance(raw,dict) else None) or (raw.get('embedding') if isinstance(raw,dict) else None)
    if not isinstance(vec,list) or len(vec)!=EMBED_DIM:raise RuntimeError(f'embedding_dimension_invalid:{len(vec) if isinstance(vec,list) else "none"}:expected:{EMBED_DIM}')
    return [float(x) for x in vec]


def process_one():
    if not OPENSEARCH:return False
    with psycopg.connect(DB) as c:
      with c.transaction():
        row=c.execute("""select id,tenant_id,domain,document_id,chunk_index,text_content,metadata,document_title,source_locator,page_number,section_id,
          scope_id,municipality_ibge,visibility,knowledge_status,retrieval_allowed,valid_from,valid_to,recorded_at,superseded_at,document_version_id,source_snapshot_id,acl
          from ingest.document_text where indexed_at is null order by created_at for update skip locked limit 1""").fetchone()
        if not row:return False
        (rid,tenant,domain,doc,idx,text,metadata,title,locator,page_number,section_id,scope_id,municipality_ibge,visibility,knowledge_status,retrieval_allowed,
         valid_from,valid_to,recorded_at,superseded_at,document_version_id,source_snapshot_id,acl)=row
      try:
        payload={
          'tenant_id':str(tenant) if tenant else None,'domain':domain,'document_id':str(doc),'chunk_index':idx,'text':text,
          'title':title or f'{domain}:{doc}','locator':locator or f'document:{doc}#chunk-{idx}','visibility':visibility or 'PRIVATE',
          'knowledge_status':knowledge_status or 'DRAFT','retrieval_allowed':bool(retrieval_allowed),'metadata':metadata or {},'acl':acl or {}
        }
        optional={'page_number':page_number,'section_id':section_id,'scope_id':scope_id,'municipality_ibge':municipality_ibge,
                  'valid_from':valid_from,'valid_to':valid_to,'recorded_at':recorded_at,'superseded_at':superseded_at,'document_version_id':document_version_id,'source_snapshot_id':source_snapshot_id}
        for k,v in optional.items():
            if v is not None:payload[k]=str(v) if k in {'document_version_id','source_snapshot_id'} else v.isoformat() if hasattr(v,'isoformat') else v
        vector=embed(text) if retrieval_allowed else None
        if vector is not None:
            payload.update(
                embedding=vector,
                embedding_model=EMBED_MODEL,
                embedding_revision=EMBED_REVISION,
                embedding_dimension=EMBED_DIM,
                embedding_fingerprint=_embedding_fingerprint(),
            )
        r=requests.put(f'{OPENSEARCH}/{INDEX}/_doc/{rid}',json=payload,auth=_auth(),timeout=20);r.raise_for_status()
        with c.transaction():c.execute('update ingest.document_text set indexed_at=now(),index_error=null where id=%s',(rid,))
      except Exception as exc:
        with c.transaction():c.execute('update ingest.document_text set index_error=%s where id=%s',(str(exc)[:1000],rid))
        raise
    return True


def main():
    if not OPENSEARCH:
      print('ai-ingest disabled: OPENSEARCH_URL not configured',flush=True)
      while True:time.sleep(60)
    ensure_index()
    fingerprint=_embedding_fingerprint()
    print(f'ai-ingest index={INDEX} embeddings={bool(EMBED_ENDPOINT and EMBED_MODEL and EMBED_KEY)} model={EMBED_MODEL or "none"} revision={EMBED_REVISION or "none"} dimension={EMBED_DIM} fingerprint={(fingerprint or "none")[:12]}',flush=True)
    while True:
      try:
        if not process_one():time.sleep(INTERVAL)
      except Exception as exc:print('ai-ingest error',repr(exc),flush=True);time.sleep(5)

if __name__=='__main__':main()
