import {Body,Controller,Get,HttpException,Param,Post,Query,Req} from '@nestjs/common';
import {createHash} from 'crypto';
import {Pool} from 'pg';
import {AuthService} from '../auth.service';
import {tenantTx} from '../common/tenant-db';
import {effectivePermissions,exportManifest,requirePermission} from './v20-governance';

const pool=new Pool({connectionString:process.env.PLATFORM_DATABASE_URL});
function who(s:any){return String(s?.id||s?.sub||s?.email||'');}
async function audit(c:any,tenantId:string,actor:string,action:string,entityType:string,entityId:any,after:any){await c.query(`insert into municipality.audit_event_v20(municipality_tenant_id,actor,action,entity_type,entity_id,after_state) values($1,$2,$3,$4,$5,$6::jsonb)`,[tenantId,actor,action,entityType,entityId?String(entityId):null,JSON.stringify(after||{})]);}

@Controller('api/v1/municipality/v20')
export class MunicipalityExportV20Controller{
  constructor(private readonly auth:AuthService){}
  private async context(req:any,permission:string){const s=await this.auth.get(req.cookies?.ld_session);if(!s?.organizationId)throw new HttpException('unauthorized',401);return tenantTx(pool,s.organizationId,async c=>{const mt=(await c.query(`select id,municipality_ibge,status from municipality.tenant where organization_id=$1 order by created_at desc limit 1`,[s.organizationId])).rows[0];if(!mt)throw new HttpException('municipality_not_onboarded',404);const sid=who(s);const refs=[sid,String(s.email||'')].filter(Boolean);const roles=(await c.query(`select * from municipality.member_role where municipality_tenant_id=$1 and status='ACTIVE' and subject_id=any($2::text[])`,[mt.id,refs])).rows;const permissions=effectivePermissions(roles);try{requirePermission(permissions,permission)}catch{throw new HttpException('municipal_permission_denied',403)}return{s,mt,sid,permissions};});}

  @Post('exports')
  async create(@Req() req:any){const x=await this.context(req,'export.create');return tenantTx(pool,x.s.organizationId,async c=>{const datasets=(await c.query(`select dataset_code,kind,visibility,status from municipality.dataset where municipality_tenant_id=$1 order by dataset_code`,[x.mt.id])).rows;const specs:[string,string][]=[
      ['departments',`select count(*)::bigint n from municipality.department where municipality_tenant_id=$1`],
      ['member_roles',`select count(*)::bigint n from municipality.member_role where municipality_tenant_id=$1`],
      ['datasets',`select count(*)::bigint n from municipality.dataset where municipality_tenant_id=$1`],
      ['dataset_snapshots',`select count(*)::bigint n from municipality.dataset_snapshot where municipality_tenant_id=$1`],
      ['ctm',`select count(*)::bigint n from municipality.ctm_parcel where municipality_tenant_id=$1`],
      ['iptu',`select count(*)::bigint n from municipality.iptu_record where municipality_tenant_id=$1`],
      ['pgv',`select count(*)::bigint n from municipality.pgv_value where municipality_tenant_id=$1`],
      ['itbi',`select count(*)::bigint n from municipality.itbi_record where municipality_tenant_id=$1`],
      ['licensing',`select count(*)::bigint n from municipality.licensing_case where municipality_tenant_id=$1`],
      ['publication_events',`select count(*)::bigint n from municipality.publication_event_v20 where municipality_tenant_id=$1`],
      ['audit',`select count(*)::bigint n from municipality.audit_event_v20 where municipality_tenant_id=$1`]
    ];const counts:any={};for(const [name,sql] of specs)counts[name]=Number((await c.query(sql,[x.mt.id])).rows[0]?.n||0);const generatedAt=new Date().toISOString();const manifest=exportManifest({municipality_ibge:x.mt.municipality_ibge,generated_at:generatedAt,datasets,counts});const checksum=createHash('sha256').update(JSON.stringify(manifest)).digest('hex');const r=(await c.query(`insert into municipality.export_job(municipality_tenant_id,status,requested_by,manifest,checksum_sha256,expires_at) values($1,'READY',$2,$3::jsonb,$4,now()+interval '30 days') returning id,status,manifest,checksum_sha256,created_at,expires_at`,[x.mt.id,x.sid,JSON.stringify(manifest),checksum])).rows[0];await audit(c,x.mt.id,x.sid,'EXPORT_CREATED','municipality.export_job',r.id,{checksum_sha256:checksum,counts});return r;});}

  @Post('exports/:id/materialize')
  async materialize(@Req() req:any,@Param('id') id:string){const x=await this.context(req,'export.create');return tenantTx(pool,x.s.organizationId,async c=>{const job=(await c.query(`select * from municipality.export_job where id=$1 and municipality_tenant_id=$2 and status='READY' and (expires_at is null or expires_at>now()) for update`,[id,x.mt.id])).rows[0];if(!job)throw new HttpException('ready_export_not_found',404);await c.query(`delete from municipality.export_chunk where export_job_id=$1`,[id]);const specs:[string,string][]=[
      ['departments',`select id,code,name,status,created_at from municipality.department where municipality_tenant_id=$1 order by code`],
      ['member_roles',`select id,department_id,subject_id,role,permission_overrides,status,created_at,revoked_at from municipality.member_role where municipality_tenant_id=$1 order by created_at,id`],
      ['datasets',`select id,dataset_code,title,kind,visibility,source_id,status,publication_policy,created_at,updated_at from municipality.dataset where municipality_tenant_id=$1 order by dataset_code`],
      ['dataset_acl',`select id,dataset_id,principal_kind,principal_value,permissions,created_at from municipality.dataset_acl where municipality_tenant_id=$1 order by dataset_id,principal_kind,principal_value`],
      ['dataset_snapshots',`select id,dataset_id,source_snapshot_id,base_date,status,validation,st_asgeojson(impact_geom)::jsonb impact_geometry,checksum_manifest,validated_by,validated_at,published_by,published_at,superseded_at,revoked_at,created_at from municipality.dataset_snapshot where municipality_tenant_id=$1 order by dataset_id,created_at`],
      ['ctm',`select id,cadastral_code,st_asgeojson(geom)::jsonb geometry,attributes,source_snapshot_id,valid_from,valid_to from municipality.ctm_parcel where municipality_tenant_id=$1 order by cadastral_code,valid_from`],
      ['iptu',`select id,cadastral_code,reference_year,land_value_cents,building_value_cents,tax_value_cents,attributes,source_snapshot_id,created_at,updated_at from municipality.iptu_record where municipality_tenant_id=$1 order by reference_year,cadastral_code`],
      ['pgv',`select id,cadastral_code,zone_code,reference_year,land_value_cents_m2,building_value_cents_m2,source_snapshot_id,valid_from,valid_to,attributes,created_at from municipality.pgv_value where municipality_tenant_id=$1 order by reference_year,zone_code,cadastral_code`],
      ['itbi',`select id,protocol,cadastral_code,transaction_date,declared_value_cents,assessed_value_cents,tax_value_cents,source_snapshot_id,attributes,created_at from municipality.itbi_record where municipality_tenant_id=$1 order by created_at,id`],
      ['licensing',`select id,case_type,protocol,cadastral_code,property_id,status,applicant_ref,evidence_ids,source_snapshot_ids,decision_reason,decided_by,decided_at,metadata,created_at,updated_at from municipality.licensing_case where municipality_tenant_id=$1 order by created_at,id`],
      ['publication_events',`select id,dataset_id,action,previous_dataset_snapshot_id,new_dataset_snapshot_id,actor,reason,affected_property_count,metadata,created_at from municipality.publication_event_v20 where municipality_tenant_id=$1 order by created_at,id`],
      ['audit',`select id,actor,action,entity_type,entity_id,before_state,after_state,evidence_ids,created_at from municipality.audit_event_v20 where municipality_tenant_id=$1 order by created_at,id`]
    ];const chunkHashes:string[]=[];let total=0;const page=1000;for(const [name,baseSql] of specs){let offset=0,ordinal=0;for(;;){const rows=(await c.query(`${baseSql} limit $2 offset $3`,[x.mt.id,page,offset])).rows;if(!rows.length)break;const raw=JSON.stringify(rows);const sha=createHash('sha256').update(raw).digest('hex');await c.query(`insert into municipality.export_chunk(municipality_tenant_id,export_job_id,dataset_name,ordinal,row_count,payload,sha256) values($1,$2,$3,$4,$5,$6::jsonb,$7)`,[x.mt.id,id,name,ordinal,rows.length,raw,sha]);chunkHashes.push(`${name}:${ordinal}:${sha}`);total+=rows.length;if(rows.length<page)break;offset+=rows.length;ordinal++;}}const bundle=createHash('sha256').update(chunkHashes.join('\n')).digest('hex');const updated=(await c.query(`update municipality.export_job set materialized_at=now(),record_count=$3,bundle_sha256=$4,checksum_sha256=$4 where id=$1 and municipality_tenant_id=$2 returning id,status,manifest,checksum_sha256,bundle_sha256,record_count,materialized_at,expires_at`,[id,x.mt.id,total,bundle])).rows[0];await audit(c,x.mt.id,x.sid,'EXPORT_MATERIALIZED','municipality.export_job',id,{bundle_sha256:bundle,record_count:total,chunks:chunkHashes.length});return{...updated,chunkCount:chunkHashes.length};});}

  @Get('exports/:id/data')
  async data(@Req() req:any,@Param('id') id:string,@Query('dataset') dataset?:string,@Query('cursor') cursorRaw?:string,@Query('limit') limitRaw?:string){const x=await this.context(req,'export.create');const cursor=Math.max(0,Number(cursorRaw||0)||0),limit=Math.max(1,Math.min(Number(limitRaw||20)||20,100));return tenantTx(pool,x.s.organizationId,async c=>{const job=(await c.query(`select id,status,checksum_sha256,bundle_sha256,record_count,materialized_at,expires_at from municipality.export_job where id=$1 and municipality_tenant_id=$2`,[id,x.mt.id])).rows[0];if(!job)throw new HttpException('export_not_found',404);if(!job.materialized_at)throw new HttpException('export_not_materialized',409);const r=await c.query(`select dataset_name,ordinal,row_count,sha256,payload from municipality.export_chunk where export_job_id=$1 and ($2::text is null or dataset_name=$2) order by dataset_name,ordinal offset $3 limit $4`,[id,dataset||null,cursor,limit+1]);const hasMore=r.rows.length>limit;return{export:job,items:hasMore?r.rows.slice(0,limit):r.rows,nextCursor:hasMore?cursor+limit:null};});}

  @Post('offboarding')
  async offboarding(@Req() req:any,@Body() b:any){const x=await this.context(req,'offboarding.manage');const reason=String(b?.reason||'').trim();if(!b?.exportJobId||!reason)throw new HttpException('exportJobId_and_reason_required',400);return tenantTx(pool,x.s.organizationId,async c=>{const exp=(await c.query(`select id,status,materialized_at,expires_at from municipality.export_job where id=$1 and municipality_tenant_id=$2 and status='READY' and materialized_at is not null and (expires_at is null or expires_at>now())`,[b.exportJobId,x.mt.id])).rows[0];if(!exp)throw new HttpException('materialized_ready_export_required_before_offboarding',409);const r=(await c.query(`insert into municipality.offboarding_case(municipality_tenant_id,export_job_id,status,requested_by,reason) values($1,$2,'REQUESTED',$3,$4) returning *`,[x.mt.id,b.exportJobId,x.sid,reason])).rows[0];await c.query(`update municipality.dataset set status='OFFBOARDING',updated_at=now() where municipality_tenant_id=$1 and status<>'INACTIVE'`,[x.mt.id]);await c.query(`update municipality.tenant set status='OFFBOARDING' where id=$1`,[x.mt.id]);await audit(c,x.mt.id,x.sid,'OFFBOARDING_REQUESTED','municipality.offboarding_case',r.id,{export_job_id:b.exportJobId,reason});return r;});}

  @Post('offboarding/:id/approve')
  async approve(@Req() req:any,@Param('id') id:string){const x=await this.context(req,'offboarding.manage');return tenantTx(pool,x.s.organizationId,async c=>{const before=(await c.query(`select * from municipality.offboarding_case where id=$1 and municipality_tenant_id=$2 for update`,[id,x.mt.id])).rows[0];if(!before)throw new HttpException('offboarding_not_found',404);if(before.status!=='REQUESTED')throw new HttpException('offboarding_not_requestable',409);if(String(before.requested_by)===x.sid)throw new HttpException('offboarding_requires_second_actor',409);const r=(await c.query(`update municipality.offboarding_case set status='APPROVED',approved_by=$3 where id=$1 and municipality_tenant_id=$2 returning *`,[id,x.mt.id,x.sid])).rows[0];await audit(c,x.mt.id,x.sid,'OFFBOARDING_APPROVED','municipality.offboarding_case',id,{requested_by:r.requested_by,approved_by:r.approved_by});return r;});}

  @Post('offboarding/:id/complete')
  async complete(@Req() req:any,@Param('id') id:string){const x=await this.context(req,'offboarding.manage');return tenantTx(pool,x.s.organizationId,async c=>{const before=(await c.query(`select * from municipality.offboarding_case where id=$1 and municipality_tenant_id=$2 for update`,[id,x.mt.id])).rows[0];if(!before)throw new HttpException('offboarding_not_found',404);if(before.status!=='APPROVED'||!before.approved_by)throw new HttpException('approved_offboarding_required',409);const r=(await c.query(`update municipality.offboarding_case set status='COMPLETED',completed_at=now() where id=$1 and municipality_tenant_id=$2 returning *`,[id,x.mt.id])).rows[0];await c.query(`update municipality.dataset set status='INACTIVE',updated_at=now() where municipality_tenant_id=$1`,[x.mt.id]);await c.query(`update municipality.member_role set status='REVOKED',revoked_at=coalesce(revoked_at,now()) where municipality_tenant_id=$1 and status='ACTIVE'`,[x.mt.id]);await c.query(`update municipality.tenant set status='OFF' where id=$1`,[x.mt.id]);await audit(c,x.mt.id,x.sid,'OFFBOARDING_COMPLETED','municipality.offboarding_case',id,{approved_by:r.approved_by,completed_at:r.completed_at});return r;});}
}
