# yaml-language-server: $schema=https://raw.githubusercontent.com/maplibre/martin/main/schemas/config.json
listen_addresses: 0.0.0.0:3000
route_prefix: /tiles
cache:
  size_mb: 128
  tile_size_mb: 96
  cache_control: "public, max-age=300"
postgres:
  connection_string: ${DATABASE_URL}
  default_srid: 4326
  auto_bounds: quick
  auto_publish:
    from_schemas: [tiles]
    functions: false
    tables:
      from_schemas: [tiles]
      id_columns: [id]
      source_id_format: "{table}"
      clip_geom: true
      extent: 4096
      buffer: 64
  max_feature_count: 50000
  pool_size: 10
