export type RouteContract={method:'get'|'post'|'put'|'patch'|'delete';path:string;summary:string;tags:string[];auth:'public'|'session'|'admin'|'internal';idempotent?:boolean;stream?:'sse'};

export const routeCatalog:RouteContract[]=[
  {method:'get',path:'/api/v1/health',summary:'Health da Platform API',tags:['system'],auth:'public'},
  {method:'get',path:'/api/v1/auth/me',summary:'Sessão autenticada atual',tags:['iam'],auth:'session'},
  {method:'get',path:'/api/v1/municipalities',summary:'Busca municípios do catálogo IBGE',tags:['core'],auth:'session'},
  {method:'get',path:'/api/v1/municipalities/{ibge}/coverage',summary:'Cobertura de fontes/datasets do município',tags:['source','municipality'],auth:'session'},
  {method:'get',path:'/api/v1/municipality-labs/{ibge}/validation-cases',summary:'Casos de validação manual do município laboratório',tags:['municipality','qa'],auth:'admin'},
  {method:'post',path:'/api/v1/municipality-labs/{ibge}/validation-cases',summary:'Registra caso de validação oficial do município laboratório',tags:['municipality','qa'],auth:'admin'},
  {method:'post',path:'/api/v1/municipality-labs/{ibge}/validation-cases/{caseId}/review',summary:'Revisa caso de validação com referência oficial',tags:['municipality','qa'],auth:'admin'},
  {method:'get',path:'/api/v1/sources/coverage',summary:'Cobertura/versionamento de fontes',tags:['source'],auth:'session'},
  {method:'post',path:'/api/v1/sources/ibge/municipalities/sync',summary:'Sincroniza catálogo oficial de municípios IBGE',tags:['source'],auth:'admin',idempotent:true},
  {method:'get',path:'/api/v1/parcel/resolve',summary:'Compatibilidade: resolve parcela por coordenada e data-base',tags:['geo'],auth:'session'},
  {method:'post',path:'/api/v1/parcel/resolve',summary:'Resolve parcela por ponto, polígono, endereço indexado ou identificador',tags:['geo'],auth:'session'},
  {method:'get',path:'/api/v1/legal/search',summary:'Busca estrutura jurídica versionada',tags:['legal'],auth:'session'},
  {method:'get',path:'/api/v1/legal/rules/effective',summary:'Regras CONFIRMED vigentes por município/zona/data-base',tags:['legal'],auth:'session'},
  {method:'post',path:'/api/v1/spatial/intersections',summary:'Interseções reproduzíveis contra camadas publicadas',tags:['geo','analysis'],auth:'session'},
  {method:'get',path:'/api/v1/nearby',summary:'Proximidade a equipamentos/infra/camadas',tags:['geo','analysis'],auth:'session'},
  {method:'post',path:'/api/v1/analysis',summary:'Executa análise territorial temporal e congela evidências',tags:['analysis'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/analysis/{id}/evidence',summary:'Evidências, snapshots, relações e cálculos de uma análise',tags:['analysis','evidence'],auth:'session'},
  {method:'post',path:'/api/v1/reports',summary:'Enfileira relatório técnico',tags:['report'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/reports/{id}',summary:'Consulta execução/artefato de relatório',tags:['report'],auth:'session'},
  {method:'get',path:'/api/v1/reports/{id}/manifest',summary:'Consulta snapshot, seções, evidências e artefatos congelados',tags:['report','evidence'],auth:'session'},
  {method:'get',path:'/api/v1/reports/{id}/sections',summary:'Consulta as 20 seções estruturadas do Relatório 360',tags:['report'],auth:'session'},
  {method:'post',path:'/api/v1/reports/{id}/share',summary:'Cria token de compartilhamento controlado (resolução pública ainda desabilitada)',tags:['report'],auth:'session'},
  {method:'get',path:'/api/v1/events/jobs/{id}',summary:'Acompanha job por Server-Sent Events',tags:['jobs'],auth:'session',stream:'sse'},
  {method:'get',path:'/api/v1/property360/properties',summary:'Lista imóveis do workspace',tags:['property360'],auth:'session'},
  {method:'post',path:'/api/v1/property360/properties/from-analysis',summary:'Salva uma Ficha 360 a partir de análise/parcela resolvida',tags:['property360'],auth:'session'},
  {method:'get',path:'/api/v1/property360/properties/{id}/ficha',summary:'Ficha 360 agregada com análises, AVM, CRM, diligências e relatórios',tags:['property360'],auth:'session'},
  {method:'post',path:'/api/v1/property360/properties/{id}/notes',summary:'Registra nota auditável do imóvel',tags:['property360','crm'],auth:'session'},
  {method:'post',path:'/api/v1/property360/diligences',summary:'Cria diligência para imóvel/empreendimento',tags:['property360','crm'],auth:'session'},
  {method:'get',path:'/api/v1/property360/developments',summary:'Lista empreendimentos',tags:['property360'],auth:'session'},
  {method:'get',path:'/api/v1/property360/comparables',summary:'Busca comparáveis disponíveis',tags:['market'],auth:'session'},
  {method:'post',path:'/api/v1/property360/avm',summary:'Executa AVM determinístico',tags:['market'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/rural/assets',summary:'Lista ativos rurais',tags:['rural'],auth:'session'},
  {method:'post',path:'/api/v1/rural/assets',summary:'Cria ativo rural privado do workspace',tags:['rural'],auth:'session'},
  {method:'get',path:'/api/v1/rural/assets/{id}/detail',summary:'Ficha operacional do ativo rural',tags:['rural'],auth:'session'},
  {method:'post',path:'/api/v1/rural/assets/{id}/registry-records',summary:'Adiciona registro normalizado com provenance obrigatório para fontes oficiais',tags:['rural','registry'],auth:'session'},
  {method:'post',path:'/api/v1/rural/assets/{id}/registry-records/{recordId}/identifiers',summary:'Adiciona identificador cadastral não pessoal',tags:['rural','identity'],auth:'session'},
  {method:'get',path:'/api/v1/rural/search',summary:'Busca rural unificada por registro, texto e proximidade',tags:['rural','search'],auth:'session'},
  {method:'get',path:'/api/v1/rural/assets/{id}/identity-graph',summary:'Grafo CAR/SNCR/SIGEF/CIB e convergências sem fusão jurídica',tags:['rural','identity'],auth:'session'},
  {method:'post',path:'/api/v1/rural/assets/{id}/identity-graph/rebuild',summary:'Recalcula vínculos candidatos por identificadores/geometria',tags:['rural','identity'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/rural/assets/{id}/monitors/{monitorId}/check',summary:'Executa diff reproduzível das camadas monitoradas',tags:['rural','monitoring'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/rural/assets/{id}/exports',summary:'Enfileira exportação KML/KMZ',tags:['rural','export'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/rural/exports/{id}',summary:'Consulta artefato KML/KMZ e hash',tags:['rural','export'],auth:'session'},
  {method:'post',path:'/api/v1/rural/identity-links/{linkId}/review',summary:'Revisão humana de vínculo candidato do identity graph',tags:['rural','identity'],auth:'admin'},
  {method:'post',path:'/api/v1/rural/assets/{id}/report',summary:'Enfileira dossiê RE Rural 360',tags:['rural','report'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/rural/assets/{id}/overlaps/recalculate',summary:'Recalcula sobreposições rurais',tags:['rural'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/condominiums',summary:'Lista condomínios',tags:['condo'],auth:'session'},
  {method:'get',path:'/api/v1/condominiums/{id}/dashboard',summary:'Dashboard Condomínio 360',tags:['condo'],auth:'session'},
  {method:'get',path:'/api/v1/condominiums/{id}/units',summary:'Lista unidades do condomínio',tags:['condo'],auth:'session'},
  {method:'get',path:'/api/v1/condominiums/{id}/common-areas',summary:'Lista áreas comuns',tags:['condo'],auth:'session'},
  {method:'post',path:'/api/v1/condominiums/{id}/works',summary:'Submete obra/reforma para workflow',tags:['condo'],auth:'session'},
  {method:'get',path:'/api/v1/condominiums/{id}/assemblies',summary:'Lista assembleias e governança',tags:['condo'],auth:'session'},
  {method:'post',path:'/api/v1/condominiums/{id}/report',summary:'Enfileira relatório Condomínio 360',tags:['condo','report'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/solar/projects/{id}/dashboard',summary:'Dashboard Solar 360',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/sites',summary:'Cria site solar versionável',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/layouts/auto',summary:'Gera layout 2D preliminar determinístico',tags:['solar'],auth:'session',idempotent:true},
  {method:'get',path:'/api/v1/solar/projects/{id}/scene-3d',summary:'Cena estrutural para preview 3D preliminar',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/energy-balance',summary:'Calcula autoconsumo/injeção/compra mensal',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/electrical-design',summary:'Dimensiona strings/MPPT com dados explícitos de datasheet',tags:['solar'],auth:'session'},
  {method:'get',path:'/api/v1/solar/projects/{id}/electrical-designs',summary:'Lista dimensionamentos elétricos preliminares',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/sun-path',summary:'Trajetória solar preliminar do dia',tags:['solar'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/report',summary:'Enfileira relatório Energia Solar 360',tags:['solar','report'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/ai/chat',summary:'Consulta assistente especializado com grounding',tags:['ai'],auth:'session'},
  {method:'post',path:'/api/v1/solar/projects/{id}/simulate',summary:'Executa cenário solar reproduzível',tags:['solar'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/aitec/projects/{id}/scenarios/generate',summary:'Gera cenário preliminar A.I TEC',tags:['aitec'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/aitec/projects/{id}/solutions/generate',summary:'Gera alternativas geometry-aware com hard constraints',tags:['aitec'],auth:'session',idempotent:true},
  {method:'post',path:'/api/v1/aitec/solutions/{solutionId}/locks',summary:'Trava objetos geométricos para regeneração',tags:['aitec'],auth:'session'},
  {method:'post',path:'/api/v1/aitec/solutions/{solutionId}/branch',summary:'Cria branch preservando objetos travados',tags:['aitec'],auth:'session'},
  {method:'post',path:'/api/v1/aitec/solutions/{solutionId}/export-geojson',summary:'Exporta solução A.I TEC em GeoJSON',tags:['aitec'],auth:'session'},
  {method:'post',path:'/api/v1/aitec/solutions/{solutionId}/export-csv',summary:'Exporta quadro de métricas A.I TEC em CSV',tags:['aitec'],auth:'session'},
  {method:'get',path:'/api/v1/municipality/workspace',summary:'Lista workspaces municipais',tags:['municipality'],auth:'session'},
];
