import {Body,Controller,Get,HttpException,Param,Post,Req} from '@nestjs/common';
import {createHash} from 'crypto';
import {Pool} from 'pg';
import {AuthService} from '../auth.service';
import {tenantTx} from '../common/tenant-db';
import {RURAL_CONNECTOR_CODES,readinessMatrix,recordGoldenReview} from './v20-readiness';

const pool=new Pool({connectionString:process.env.PLATFORM_DATABASE_URL});

@Controller('api/v1/rural/v20')
export class RuralV20Controller{
  constructor(private readonly auth:AuthService){}
  private async session(req:any,admin=false){const s=await this.auth.get(req.cookies?.ld_session);if(!s?.organizationId)throw new HttpException('unauthorized',401);const modules=Array.isArray(s.entitlements?.modules)?s.entitlements.modules:[];if(!s.roles?.includes('admin')&&!modules.includes('re-rural'))throw new HttpException('module_not_entitled',403);if(admin&&!s.roles?.includes('admin'))throw new HttpException('forbidden',403);return s;}

  @Get('connectors')
  async connectors(@Req() req:any){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{const rows=(await c.query(`select cat.code,cat.authority,cat.data_family,cat.legal_notes,cat.external_gate,cfg.id config_id,cfg.source_id,cfg.access_mode,cfg.legal_availability,cfg.status registry_status,cfg.configuration from rural.connector_catalog cat left join rural.connector_config cfg on cfg.connector_code=cat.code and cfg.tenant_id=$1 order by cat.code`,[s.organizationId])).rows;return{items:rows,policy:'Catalog presence is not homologation. Each connector remains an external gate until a real source run carries publication, validation, license and checksum evidence.'};});}

  @Post('connectors/:code/configure')
  async configure(@Req() req:any,@Param('code') rawCode:string,@Body() body:any){const s=await this.session(req,true);const code=rawCode.toUpperCase();if(!RURAL_CONNECTOR_CODES.includes(code as any))throw new HttpException('unknown_connector_code',404);const sourceId=body?.sourceId?String(body.sourceId):null,accessMode=String(body?.accessMode||'').trim(),legalAvailability=String(body?.legalAvailability||'').trim();if(!sourceId||!accessMode||!legalAvailability)throw new HttpException('sourceId/accessMode/legalAvailability obrigatórios',400);return tenantTx(pool,s.organizationId,async c=>{const src=await c.query(`select id,code,authority,access_class,license_terms from source.registry where id=$1`,[sourceId]);if(!src.rowCount)throw new HttpException('source_registry_not_found',404);const r=await c.query(`insert into rural.connector_config(tenant_id,connector_code,source_id,access_mode,legal_availability,status,configuration) values($1,$2,$3,$4,$5,'CONFIGURED',$6::jsonb) on conflict(tenant_id,connector_code) do update set source_id=excluded.source_id,access_mode=excluded.access_mode,legal_availability=excluded.legal_availability,status='CONFIGURED',configuration=excluded.configuration,updated_at=now() returning id,connector_code,source_id,access_mode,legal_availability,status,configuration,updated_at`,[s.organizationId,code,sourceId,accessMode,legalAvailability,JSON.stringify(body?.configuration||{})]);return{...r.rows[0],homologated:false,sourceRegistry:src.rows[0]};});}

  @Post('connectors/:code/runs')
  async run(@Req() req:any,@Param('code') rawCode:string,@Body() body:any){const s=await this.session(req,true);const code=rawCode.toUpperCase();if(!RURAL_CONNECTOR_CODES.includes(code as any))throw new HttpException('unknown_connector_code',404);const snapshotId=String(body?.sourceSnapshotId||''),executionStatus=String(body?.executionStatus||'').toUpperCase();if(!snapshotId||!['SUCCEEDED','FAILED'].includes(executionStatus))throw new HttpException('sourceSnapshotId/executionStatus inválidos',400);return tenantTx(pool,s.organizationId,async c=>{
    const cfg=await c.query(`select id,source_id,access_mode,legal_availability,status from rural.connector_config where tenant_id=$1 and connector_code=$2`,[s.organizationId,code]);if(!cfg.rowCount)throw new HttpException('connector_not_configured',409);const config=cfg.rows[0];
    const ev=await c.query(`select s.id,s.source_id,s.sha256,s.source_date,s.validation_status,sr.license_terms,case when exists(select 1 from source.publication p where p.snapshot_id=s.id and p.status='ACTIVE') then 'ACTIVE' else null end publication_status from source.snapshot s join source.registry sr on sr.id=s.source_id where s.id=$1`,[snapshotId]);if(!ev.rowCount)throw new HttpException('source_snapshot_not_found',404);const e=ev.rows[0];
    const complete=executionStatus==='SUCCEEDED'&&String(config.status)==='CONFIGURED'&&String(e.source_id)===String(config.source_id)&&String(e.validation_status).toUpperCase()==='PASS'&&e.publication_status==='ACTIVE'&&Boolean(String(e.license_terms||'').trim())&&/^[a-f0-9]{64}$/i.test(String(e.sha256||''))&&Boolean(e.source_date);
    const storedStatus=executionStatus==='FAILED'?'FAILED':complete?'SUCCEEDED':'EVIDENCE_INCOMPLETE';const requestFingerprint=createHash('sha256').update(JSON.stringify(body?.request||{})).digest('hex');
    const r=await c.query(`insert into rural.connector_run(tenant_id,connector_config_id,source_snapshot_id,run_status,records_received,records_loaded,request_fingerprint,response_sha256,metadata,started_at,completed_at,error) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,coalesce($10::timestamptz,now()),now(),$11) returning id,run_status,source_snapshot_id,records_received,records_loaded,started_at,completed_at`,[s.organizationId,config.id,snapshotId,storedStatus,body?.recordsReceived??null,body?.recordsLoaded??null,requestFingerprint,body?.responseSha256||null,JSON.stringify(body?.metadata||{}),body?.startedAt||null,executionStatus==='FAILED'?String(body?.error||'external_connector_failed'):null]);
    return{...r.rows[0],runtimeEvidenceComplete:complete,homologated:false,evidence:{validationStatus:e.validation_status,publicationStatus:e.publication_status,licensePresent:Boolean(String(e.license_terms||'').trim()),sourceSha256:e.sha256,sourceDate:e.source_date,sourceMatchesConfig:String(e.source_id)===String(config.source_id)},policy:'Successful connector execution is recorded; legal/professional truth is not inferred.'};
  });}

  @Get('readiness')
  async readiness(@Req() req:any){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{const rows=(await c.query(`select cat.code,cfg.status registry_status,cfg.access_mode,cfg.legal_availability,cfg.source_id,lr.run_status,lr.source_snapshot_id,lr.completed_at,ss.sha256 source_sha256,ss.source_date,ss.validation_status,sr.license_terms,case when exists(select 1 from source.publication p where p.snapshot_id=ss.id and p.status='ACTIVE') then 'ACTIVE' else null end publication_status from rural.connector_catalog cat left join rural.connector_config cfg on cfg.connector_code=cat.code and cfg.tenant_id=$1 left join lateral(select r.* from rural.connector_run r where r.connector_config_id=cfg.id and r.tenant_id=$1 order by r.started_at desc limit 1) lr on true left join source.snapshot ss on ss.id=lr.source_snapshot_id left join source.registry sr on sr.id=ss.source_id order by cat.code`,[s.organizationId])).rows;return readinessMatrix(rows);});}

  @Post('golden-cases')
  async golden(@Req() req:any,@Body() body:any){const s=await this.session(req);const code=String(body?.caseCode||'').trim();if(!code)throw new HttpException('caseCode obrigatório',400);const expected=body?.expected??{},actual=body?.actual??{},snapshotIds=Array.isArray(body?.sourceSnapshotIds)?body.sourceSnapshotIds.map(String):[];return tenantTx(pool,s.organizationId,async c=>{const review=recordGoldenReview({expected,actual,reviewer:body?.reviewer,professional_reference:body?.professionalReference,reviewed_at:body?.reviewedAt});const r=await c.query(`insert into rural.golden_case(tenant_id,case_code,asset_id,base_date,expected,actual,source_snapshot_ids,review_status,reviewer,professional_reference,reviewed_at,notes) values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::uuid[],$8,$9,$10,$11,$12) on conflict(tenant_id,case_code) do update set asset_id=excluded.asset_id,base_date=excluded.base_date,expected=excluded.expected,actual=excluded.actual,source_snapshot_ids=excluded.source_snapshot_ids,review_status=excluded.review_status,reviewer=excluded.reviewer,professional_reference=excluded.professional_reference,reviewed_at=excluded.reviewed_at,notes=excluded.notes returning id,case_code,base_date,review_status,reviewer,professional_reference,reviewed_at,created_at`,[s.organizationId,code,body?.assetId||null,String(body?.baseDate||new Date().toISOString().slice(0,10)),JSON.stringify(expected),JSON.stringify(actual),snapshotIds,review.status,body?.reviewer||null,body?.professionalReference||null,body?.reviewedAt||null,body?.notes||null]);return{...r.rows[0],matches:review.matches,homologated:false,policy:review.policy};});}

  @Get('golden-cases')
  async goldens(@Req() req:any){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>({items:(await c.query(`select id,case_code,asset_id,base_date,expected,actual,source_snapshot_ids,review_status,reviewer,professional_reference,reviewed_at,notes,created_at from rural.golden_case where tenant_id=$1 order by case_code`,[s.organizationId])).rows,homologated:false}));}
}
