'use client';
import {useEffect,useState} from 'react';import {Card,Badge} from '@lotediretor/ui';
async function get(url:string){const r=await fetch(url,{credentials:'include',cache:'no-store'});const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.message||`HTTP ${r.status}`);return x;}
export function AdminData({title,endpoint}:{title:string;endpoint:string}){const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{get(endpoint).then(setData).catch(e=>setError(e.message))},[endpoint]);const items=data?.items||[];const keys=items[0]?Object.keys(items[0]).filter(k=>!['metadata','evidence','rules','entitlements','details'].includes(k)).slice(0,9):[];return <><header className="ahead"><div><h1>{title}</h1><div className="sub">Control Plane conectado às APIs administrativas.</div></div><Badge tone="success">v19-rc2</Badge></header>{error&&<Card className="atable"><div className="adminError">{error}</div></Card>}{!data&&!error&&<Card className="atable">Carregando…</Card>}{data&&<Card className="atable">{data.degraded&&<div className="adminWarn">{data.message}</div>}{items.length?<table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{items.map((row:any,i:number)=><tr key={row.id||row.trace_id||i}>{keys.map(k=><td key={k}>{typeof row[k]==='object'?JSON.stringify(row[k]):String(row[k]??'—')}</td>)}</tr>)}</tbody></table>:<div className="emptyAdmin">Nenhum registro disponível.</div>}</Card>}</>}

export function AdminDashboard(){const [data,setData]=useState<any>(null);const [ready,setReady]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{Promise.all([get('/control/v1/metrics/executive'),get('/control/v1/ops/readiness')]).then(([a,b])=>{setData(a);setReady(b)}).catch(e=>setError(e.message))},[]);return <><header className="ahead"><div><h1>Control Plane</h1><div className="sub">Negócio, governança, IA, dados e operação.</div></div><Badge tone="success">v19-rc2</Badge></header>{error&&<Card className="atable"><div className="adminError">{error}</div></Card>}{data&&<><div className="akpis"><Card className="akpi"><small>Tenants ativos</small><b>{data.activeTenants}</b></Card><Card className="akpi"><small>Assinaturas</small><b>{data.activeSubscriptions}</b></Card><Card className="akpi"><small>Recebido hoje</small><b>{(data.receivedTodayCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></Card><Card className="akpi"><small>Traces IA hoje</small><b>{data.aiTracesToday}</b></Card></div><div className="akpis second"><Card className="akpi"><small>Tickets abertos</small><b>{data.openTickets}</b></Card><Card className="akpi"><small>Aprovações pendentes</small><b>{data.pendingApprovals}</b></Card><Card className="akpi"><small>Readiness</small><b>{ready?.status||'—'}</b></Card></div></>}</>}

export function AdminOps(){const [ready,setReady]=useState<any>(null);const [incidents,setIncidents]=useState<any>(null);useEffect(()=>{Promise.all([get('/control/v1/ops/readiness'),get('/control/v1/ops/incidents')]).then(([a,b])=>{setReady(a);setIncidents(b)})},[]);return <><header className="ahead"><div><h1>Operações</h1><div className="sub">Readiness, incidentes e health checks.</div></div><Badge tone="success">v19-rc2</Badge></header><Card className="atable"><h3>Readiness</h3><pre>{JSON.stringify(ready,null,2)}</pre></Card><Card className="atable"><h3>Incidentes</h3><pre>{JSON.stringify(incidents,null,2)}</pre></Card></>}

export function AdminProduct(){const [plans,setPlans]=useState<any>(null);const [deployments,setDeployments]=useState<any>(null);useEffect(()=>{Promise.all([get('/control/v1/catalog/plans'),get('/control/v1/deployments')]).then(([a,b])=>{setPlans(a);setDeployments(b)})},[]);return <><header className="ahead"><div><h1>Produto / Entitlements</h1><div className="sub">Planos versionados e promoção de artefatos.</div></div><Badge tone="success">v19-rc2</Badge></header><Card className="atable"><h3>Planos</h3><pre>{JSON.stringify(plans,null,2)}</pre></Card><Card className="atable"><h3>Deployments</h3><pre>{JSON.stringify(deployments,null,2)}</pre></Card></>}

export function AdminSecurity(){const [posture,setPosture]=useState<any>(null);const [audit,setAudit]=useState<any>(null);useEffect(()=>{Promise.all([get('/control/v1/security/posture'),get('/control/v1/audit')]).then(([a,b])=>{setPosture(a);setAudit(b)})},[]);return <><header className="ahead"><div><h1>Segurança</h1><div className="sub">Postura, maker-checker, webhooks e auditoria.</div></div><Badge tone="success">v19-rc2</Badge></header><Card className="atable"><pre>{JSON.stringify(posture,null,2)}</pre></Card><Card className="atable"><h3>Auditoria recente</h3><pre>{JSON.stringify(audit,null,2)}</pre></Card></>}

export function AdminDataOps(){const [sources,setSources]=useState<any>(null);const [quality,setQuality]=useState<any>(null);useEffect(()=>{Promise.all([get('/control/v1/data-ops/sources'),get('/control/v1/data-ops/quality')]).then(([a,b])=>{setSources(a);setQuality(b)})},[]);return <><header className="ahead"><div><h1>Data Ops</h1><div className="sub">Source Registry, snapshots e quality gates.</div></div><Badge tone="success">v19-rc2</Badge></header><Card className="atable"><h3>Fontes</h3><pre>{JSON.stringify(sources,null,2)}</pre></Card><Card className="atable"><h3>Qualidade</h3><pre>{JSON.stringify(quality,null,2)}</pre></Card></>}
