import {Body,Controller,Get,HttpException,Param,Post,Query,Req} from '@nestjs/common';
import {Pool} from 'pg';
import {AuthService} from '../auth.service';
import {tenantTx} from '../common/tenant-db';
import {withIdempotency} from '../common/idempotency';
import {enqueueOutbox} from '../common/outbox';

const pool=new Pool({connectionString:process.env.PLATFORM_DATABASE_URL});
function asDate(v:any){const s=String(v||new Date().toISOString().slice(0,10));if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new HttpException('baseDate deve estar em YYYY-MM-DD',400);return s;}

@Controller('api/v1/condominiums')
export class CondoController{
  constructor(private readonly auth:AuthService){}
  private async session(req:any){const s=await this.auth.get(req.cookies?.ld_session);if(!s?.organizationId)throw new HttpException('unauthorized',401);const modules=Array.isArray(s.entitlements?.modules)?s.entitlements.modules:[];if(!s.roles?.includes('admin')&&!modules.includes('condominio'))throw new HttpException('module_not_entitled',403);return s;}
  private async manager(req:any){const s=await this.session(req);if(!s.roles?.some((x:string)=>x==='admin'||x==='condo_manager'))throw new HttpException('forbidden',403);return s;}
  private async own(c:any,id:string,tenant:string){const r=await c.query('select id,name,kind,municipality_ibge from condo.condominium where id=$1 and tenant_id=$2',[id,tenant]);if(!r.rowCount)throw new HttpException('condominium_not_found',404);return r.rows[0];}

  @Get(':id/dashboard')
  async dashboard(@Req() req:any,@Param('id') id:string,@Query('baseDate') baseDateRaw?:string){const s=await this.session(req);const baseDate=asDate(baseDateRaw);return tenantTx(pool,s.organizationId,async c=>{const condo=await this.own(c,id,s.organizationId);const q=async(sql:string,p:any[]=[])=>Number((await c.query(sql,p)).rows[0]?.n||0);return{condominium:condo,baseDate,counters:{buildings:await q('select count(*) n from condo.building where condominium_id=$1',[id]),units:await q("select count(*) n from condo.unit where condominium_id=$1 and status='ACTIVE'",[id]),commonAreas:await q('select count(*) n from condo.common_area where condominium_id=$1',[id]),documents:await q('select count(*) n from condo.document where condominium_id=$1',[id]),confirmedRules:await q("select count(*) n from condo.rule where condominium_id=$1 and status='CONFIRMED' and (valid_from is null or valid_from <= $2::date + interval '1 day') and (valid_to is null or valid_to > $2::date)",[id,baseDate]),openWorks:await q("select count(*) n from condo.work_request where condominium_id=$1 and status not in ('APPROVED','REJECTED','CLOSED')",[id]),upcomingAssemblies:await q("select count(*) n from condo.assembly where condominium_id=$1 and status in ('SCHEDULED','OPEN')",[id]),maintenanceDue:await q("select count(*) n from condo.maintenance_item where condominium_id=$1 and status='ACTIVE' and next_due_at is not null and next_due_at <= current_date + 30",[id]),openOccurrences:await q("select count(*) n from condo.occurrence where condominium_id=$1 and status='OPEN'",[id]),pendingCompliance:await q("select count(*) n from condo.compliance_item where condominium_id=$1 and status not in ('COMPLIANT','WAIVED')",[id])},rule:'Documentos privados e regras sempre permanecem isolados pelo tenant; decisões automáticas não aplicam multa ou alteração cadastral.'};});}

  @Get(':id/buildings')
  async buildings(@Req() req:any,@Param('id') id:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query('select * from condo.building where condominium_id=$1 order by code',[id])).rows};});}
  @Post(':id/buildings')
  async createBuilding(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.building(tenant_id,condominium_id,code,name,floors,metadata) values($1,$2,$3,$4,$5,$6::jsonb) returning *`,[s.organizationId,id,String(body?.code||'BL-A'),String(body?.name||'Bloco'),body?.floors??null,JSON.stringify(body?.metadata||{})])).rows[0];});}

  @Get(':id/units')
  async units(@Req() req:any,@Param('id') id:string,@Query('buildingId') buildingId?:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query(`select u.*,b.name building_name from condo.unit u left join condo.building b on b.id=u.building_id where u.condominium_id=$1 and ($2::uuid is null or u.building_id=$2) order by b.code nulls first,u.code`,[id,buildingId||null])).rows};});}
  @Post(':id/units')
  async createUnit(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.unit(tenant_id,condominium_id,building_id,code,kind,floor_label,private_area_m2,fraction,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) returning *`,[s.organizationId,id,body?.buildingId||null,String(body?.code||''),String(body?.kind||'UNIT'),body?.floorLabel||null,body?.privateAreaM2??null,body?.fraction??null,JSON.stringify(body?.metadata||{})])).rows[0];});}

  @Get(':id/common-areas')
  async areas(@Req() req:any,@Param('id') id:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query('select * from condo.common_area where condominium_id=$1 order by code',[id])).rows};});}
  @Post(':id/common-areas')
  async createArea(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.common_area(tenant_id,condominium_id,code,name,kind,area_m2,usage_policy,metadata) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb) returning *`,[s.organizationId,id,String(body?.code||''),String(body?.name||''),String(body?.kind||'OTHER'),body?.areaM2??null,body?.usagePolicy||null,JSON.stringify(body?.metadata||{})])).rows[0];});}

  @Get(':id/works')
  async works(@Req() req:any,@Param('id') id:string,@Query('status') status?:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query(`select w.*,u.code unit_code,a.name common_area_name from condo.work_request w left join condo.unit u on u.id=w.unit_id left join condo.common_area a on a.id=w.common_area_id where w.condominium_id=$1 and ($2::text is null or w.status=$2) order by w.created_at desc`,[id,status||null])).rows};});}
  @Post(':id/works')
  async createWork(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.session(req);if(!body?.unitId&&!body?.commonAreaId)throw new HttpException('unitId ou commonAreaId é obrigatório',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const r=await c.query(`insert into condo.work_request(tenant_id,condominium_id,unit_id,common_area_id,title,description,work_type,status,art_rrt_reference,technical_responsible,submitted_by,submitted_at,evidence) values($1,$2,$3,$4,$5,$6,$7,'SUBMITTED',$8,$9,$10,now(),$11::jsonb) returning *`,[s.organizationId,id,body?.unitId||null,body?.commonAreaId||null,String(body?.title||'Obra/reforma'),body?.description||null,String(body?.workType||'REFORM'),body?.artRrtReference||null,body?.technicalResponsible||null,s.email||s.id,JSON.stringify(body?.evidence||{})]);await enqueueOutbox(c,'condo.work.submitted',{condominiumId:id,workRequestId:r.rows[0].id},{tenantId:s.organizationId,aggregateType:'condo.work_request',aggregateId:r.rows[0].id,dedupeKey:`condo.work.submitted:${r.rows[0].id}`});return r.rows[0];});}
  @Post(':id/works/:workId/decision')
  async decideWork(@Req() req:any,@Param('id') id:string,@Param('workId') workId:string,@Body() body:any){const s=await this.manager(req);const decision=String(body?.decision||'').toUpperCase();if(!['APPROVED','REJECTED','MORE_INFO'].includes(decision))throw new HttpException('decision inválida',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const r=await c.query(`update condo.work_request set status=$4,reviewed_by=$3,reviewed_at=now(),decision_reason=$5,updated_at=now() where id=$1 and condominium_id=$2 returning *`,[workId,id,s.email||s.id,decision,body?.reason||null]);if(!r.rowCount)throw new HttpException('work_request_not_found',404);await enqueueOutbox(c,'condo.work.reviewed',{condominiumId:id,workRequestId:workId,decision},{tenantId:s.organizationId,aggregateType:'condo.work_request',aggregateId:workId,dedupeKey:`condo.work.reviewed:${workId}:${decision}`});return r.rows[0];});}

  @Get(':id/assemblies')
  async assemblies(@Req() req:any,@Param('id') id:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const a=await c.query(`select a.*,(select count(*) from condo.agenda_item i where i.assembly_id=a.id) agenda_items from condo.assembly a where a.condominium_id=$1 order by a.scheduled_at desc`,[id]);return{items:a.rows};});}
  @Post(':id/assemblies')
  async createAssembly(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.assembly(tenant_id,condominium_id,kind,title,scheduled_at,status,quorum_rule,document_id,created_by) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) returning *`,[s.organizationId,id,String(body?.kind||'ASSEMBLY'),String(body?.title||'Assembleia'),body?.scheduledAt||new Date().toISOString(),String(body?.status||'SCHEDULED'),JSON.stringify(body?.quorumRule||{}),body?.documentId||null,s.email||s.id])).rows[0];});}
  @Post(':id/assemblies/:assemblyId/agenda')
  async addAgenda(@Req() req:any,@Param('id') id:string,@Param('assemblyId') assemblyId:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const assembly=await c.query('select id from condo.assembly where id=$1 and condominium_id=$2',[assemblyId,id]);if(!assembly.rowCount)throw new HttpException('assembly_not_found',404);return (await c.query(`insert into condo.agenda_item(tenant_id,assembly_id,ordinal,title,description,required_quorum,status) values($1,$2,$3,$4,$5,$6::jsonb,'OPEN') returning *`,[s.organizationId,assemblyId,Number(body?.ordinal||1),String(body?.title||'Pauta'),body?.description||null,JSON.stringify(body?.requiredQuorum||{})])).rows[0];});}
  @Post(':id/assemblies/:assemblyId/agenda/:agendaId/vote-summary')
  async voteSummary(@Req() req:any,@Param('id') id:string,@Param('assemblyId') assemblyId:string,@Param('agendaId') agendaId:string,@Body() body:any){const s=await this.manager(req);const favorable=Math.max(0,Number(body?.favorableCount||0)),contrary=Math.max(0,Number(body?.contraryCount||0)),abstention=Math.max(0,Number(body?.abstentionCount||0));const present=Math.max(0,Number(body?.presentCount??favorable+contrary+abstention)),eligible=body?.eligibleCount==null?null:Math.max(0,Number(body.eligibleCount));const fraction=body?.fractionFavorable==null?(present>0?favorable/present:null):Number(body.fractionFavorable);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const item=await c.query(`select i.id,i.required_quorum from condo.agenda_item i join condo.assembly a on a.id=i.assembly_id where i.id=$1 and i.assembly_id=$2 and a.condominium_id=$3`,[agendaId,assemblyId,id]);if(!item.rowCount)throw new HttpException('agenda_item_not_found',404);const rq=item.rows[0].required_quorum||{};const minFraction=Number(rq.minFraction??0);const minPresent=Number(rq.minPresent??0);const result=(present>=minPresent&&(fraction??0)>=minFraction)?'MET':'NOT_MET';const r=await c.query(`insert into condo.vote_summary(tenant_id,agenda_item_id,eligible_count,present_count,favorable_count,contrary_count,abstention_count,fraction_favorable,quorum_result,methodology) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) on conflict(agenda_item_id) do update set eligible_count=excluded.eligible_count,present_count=excluded.present_count,favorable_count=excluded.favorable_count,contrary_count=excluded.contrary_count,abstention_count=excluded.abstention_count,fraction_favorable=excluded.fraction_favorable,quorum_result=excluded.quorum_result,methodology=excluded.methodology,calculated_at=now() returning *`,[s.organizationId,agendaId,eligible,present,favorable,contrary,abstention,fraction,result,JSON.stringify({requiredQuorum:rq,aggregateOnly:true})]);return r.rows[0];});}
  @Post(':id/assemblies/:assemblyId/decisions')
  async createDecision(@Req() req:any,@Param('id') id:string,@Param('assemblyId') assemblyId:string,@Body() body:any){const s=await this.manager(req);const status=String(body?.status||'APPROVED').toUpperCase();if(!['APPROVED','REJECTED','PENDING'].includes(status))throw new HttpException('status inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const assembly=await c.query('select id from condo.assembly where id=$1 and condominium_id=$2',[assemblyId,id]);if(!assembly.rowCount)throw new HttpException('assembly_not_found',404);const d=await c.query(`insert into condo.decision(tenant_id,condominium_id,assembly_id,agenda_item_id,title,decision_text,status,effective_from,effective_to,generates_rule,source_locator,approved_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,case when $7='APPROVED' then now() else null end) returning *`,[s.organizationId,id,assemblyId,body?.agendaItemId||null,String(body?.title||'Deliberação'),String(body?.decisionText||''),status,body?.effectiveFrom||null,body?.effectiveTo||null,Boolean(body?.generatesRule),body?.sourceLocator||`assembly:${assemblyId}`]);let ruleId=null;if(status==='APPROVED'&&body?.generatesRule){const r=await c.query(`insert into condo.rule(tenant_id,condominium_id,document_id,rule_type,title,rule_text,status,source_locator,valid_from,valid_to) values($1,$2,null,'ASSEMBLY_DECISION',$3,$4,'CANDIDATE',$5,$6,$7) returning id`,[s.organizationId,id,String(body?.title||'Deliberação'),String(body?.decisionText||''),body?.sourceLocator||`assembly:${assemblyId}`,body?.effectiveFrom||null,body?.effectiveTo||null]);ruleId=r.rows[0].id;await c.query('update condo.decision set generated_rule_id=$2 where id=$1',[d.rows[0].id,ruleId]);}await enqueueOutbox(c,'condo.assembly.decision',{condominiumId:id,assemblyId,decisionId:d.rows[0].id,status,generatedRuleId:ruleId},{tenantId:s.organizationId,aggregateType:'condo.decision',aggregateId:d.rows[0].id,dedupeKey:`condo.assembly.decision:${d.rows[0].id}`});return{...d.rows[0],generated_rule_id:ruleId,ruleStatus:ruleId?'CANDIDATE':null};});}

  @Get(':id/maintenance')
  async maintenance(@Req() req:any,@Param('id') id:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query('select * from condo.maintenance_item where condominium_id=$1 order by next_due_at nulls last,title',[id])).rows};});}
  @Post(':id/maintenance')
  async createMaintenance(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.maintenance_item(tenant_id,condominium_id,common_area_id,system_code,title,interval_days,last_done_at,next_due_at,status,evidence) values($1,$2,$3,$4,$5,$6,$7,$8,'ACTIVE',$9::jsonb) returning *`,[s.organizationId,id,body?.commonAreaId||null,String(body?.systemCode||'GENERAL'),String(body?.title||'Manutenção'),body?.intervalDays??null,body?.lastDoneAt||null,body?.nextDueAt||null,JSON.stringify(body?.evidence||{})])).rows[0];});}

  @Get(':id/occurrences')
  async occurrences(@Req() req:any,@Param('id') id:string,@Query('status') status?:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query(`select * from condo.occurrence where condominium_id=$1 and ($2::text is null or status=$2) order by created_at desc`,[id,status||null])).rows};});}
  @Post(':id/occurrences')
  async createOccurrence(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.occurrence(tenant_id,condominium_id,unit_id,category,title,description,status,severity,opened_by,defense_due_at) values($1,$2,$3,$4,$5,$6,'OPEN',$7,$8,$9) returning *`,[s.organizationId,id,body?.unitId||null,String(body?.category||'GENERAL'),String(body?.title||'Ocorrência'),body?.description||null,String(body?.severity||'LOW'),s.email||s.id,body?.defenseDueAt||null])).rows[0];});}
  @Post(':id/occurrences/:occurrenceId/close')
  async closeOccurrence(@Req() req:any,@Param('id') id:string,@Param('occurrenceId') occurrenceId:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);const r=await c.query(`update condo.occurrence set status='CLOSED',reviewed_by=$3,resolution=$4,closed_at=now() where id=$1 and condominium_id=$2 returning *`,[occurrenceId,id,s.email||s.id,body?.resolution||null]);if(!r.rowCount)throw new HttpException('occurrence_not_found',404);return r.rows[0];});}

  @Get(':id/compliance')
  async compliance(@Req() req:any,@Param('id') id:string){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return{items:(await c.query('select * from condo.compliance_item where condominium_id=$1 order by due_at nulls last,code',[id])).rows};});}
  @Post(':id/compliance')
  async createCompliance(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,id,s.organizationId);return (await c.query(`insert into condo.compliance_item(tenant_id,condominium_id,code,title,category,status,due_at,responsible,source_rule_id,evidence) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) on conflict(condominium_id,code) do update set title=excluded.title,category=excluded.category,status=excluded.status,due_at=excluded.due_at,responsible=excluded.responsible,source_rule_id=excluded.source_rule_id,evidence=excluded.evidence returning *`,[s.organizationId,id,String(body?.code||''),String(body?.title||''),String(body?.category||'GENERAL'),String(body?.status||'PENDING'),body?.dueAt||null,body?.responsible||null,body?.sourceRuleId||null,JSON.stringify(body?.evidence||{})])).rows[0];});}

  @Post(':id/report')
  async report(@Req() req:any,@Param('id') id:string,@Body() body:any){const s=await this.session(req);const key=String(req.headers?.['idempotency-key']||'').trim()||undefined;const idem=await withIdempotency(pool,s.organizationId,`condo360.report:${id}`,key,async c=>{await this.own(c,id,s.organizationId);const tpl=await c.query("select code,version from report.template where code='CONDO360_360' and status='ACTIVE'");if(!tpl.rowCount)throw new HttpException('condo_report_template_not_found',500);const baseDate=asDate(body?.baseDate);const r=await c.query(`insert into report.report_run(tenant_id,kind,subject_type,subject_id,base_date,status,input_snapshot,template_code,template_version,metadata) values($1,'CONDO360','condominium',$2,$3,'QUEUED',$4::jsonb,$5,$6,$7::jsonb) returning id,status,template_code,template_version,created_at`,[s.organizationId,id,baseDate,JSON.stringify({condominiumId:id}),tpl.rows[0].code,tpl.rows[0].version,JSON.stringify({requestedBy:s.email||s.id,schemaVersion:'condo-360-v1'})]);await enqueueOutbox(c,'report.queued',{reportRunId:r.rows[0].id,kind:'CONDO360',subjectType:'condominium',subjectId:id,baseDate},{tenantId:s.organizationId,aggregateType:'report.report_run',aggregateId:r.rows[0].id,dedupeKey:`report.queued:${r.rows[0].id}`});return r.rows[0];});return{...idem.value,idempotency:{replayed:idem.replayed,key:key||null}};}
}
