import {Body,Controller,Get,HttpException,Param,Post,Query,Req} from '@nestjs/common';
import {createHash} from 'crypto';
import {Pool} from 'pg';
import {AuthService} from '../auth.service';
import {tenantTx} from '../common/tenant-db';
import {buildExternalSummary,buildRetrievalAcl,evaluateBallot,legalChangeDiff,parseClauseLayout,resolveRuleSet,sanctionGuard} from './v20-governance';

const pool=new Pool({connectionString:process.env.PLATFORM_DATABASE_URL});
function hash(value:any){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
function date(v:any){const s=String(v||new Date().toISOString().slice(0,10));if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw new HttpException('baseDate deve estar em YYYY-MM-DD',400);return s;}

@Controller('api/v1/condominiums/:condominiumId/v20')
export class CondoV20Controller{
  constructor(private readonly auth:AuthService){}
  private async session(req:any,manager=false){const s=await this.auth.get(req.cookies?.ld_session);if(!s?.organizationId)throw new HttpException('unauthorized',401);const modules=Array.isArray(s.entitlements?.modules)?s.entitlements.modules:[];if(!s.roles?.includes('admin')&&!modules.includes('condominio'))throw new HttpException('module_not_entitled',403);if(manager&&!s.roles?.some((r:string)=>r==='admin'||r==='condo_manager'))throw new HttpException('forbidden',403);return s;}
  private async own(c:any,id:string,tenant:string){const r=await c.query(`select id,name,kind,municipality_ibge from condo.condominium where id=$1 and tenant_id=$2`,[id,tenant]);if(!r.rowCount)throw new HttpException('condominium_not_found',404);return r.rows[0];}

  @Post('documents/:documentId/parse-clauses')
  async parse(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('documentId') documentId:string,@Body() body:any){const s=await this.manager(req);const blocks=Array.isArray(body?.blocks)?body.blocks:[];const parsed=parseClauseLayout(documentId,blocks);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const doc=await c.query(`select id from condo.document where id=$1 and condominium_id=$2 and tenant_id=$3`,[documentId,condominiumId,s.organizationId]);if(!doc.rowCount)throw new HttpException('document_not_found',404);await c.query(`delete from condo.document_clause where document_id=$1 and tenant_id=$2 and status='CANDIDATE'`,[documentId,s.organizationId]);const items=[];for(const clause of parsed.clauses){const pages=clause.citations.map((x:any)=>Number(x.page)).filter(Number.isFinite);const r=await c.query(`insert into condo.document_clause(tenant_id,condominium_id,document_id,clause_code,clause_text,page_from,page_to,citations,extraction_method,parser_version,status) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,'LAYOUT_BLOCKS',$9,'CANDIDATE') returning id,clause_code,clause_text,page_from,page_to,citations,status,parser_version,created_at`,[s.organizationId,condominiumId,documentId,clause.locator,clause.text,pages.length?Math.min(...pages):null,pages.length?Math.max(...pages):null,JSON.stringify(clause.citations),parsed.parser_version]);items.push(r.rows[0]);}return{status:parsed.status,items,policy:parsed.policy};});}

  @Post('clauses/:clauseId/review')
  async reviewClause(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('clauseId') clauseId:string,@Body() body:any){const s=await this.manager(req);const status=String(body?.status||'').toUpperCase();if(!['CONFIRMED','REJECTED'].includes(status))throw new HttpException('status deve ser CONFIRMED ou REJECTED',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.document_clause set status=$4,reviewed_by=$5,reviewed_at=now() where id=$1 and condominium_id=$2 and tenant_id=$3 returning *`,[clauseId,condominiumId,s.organizationId,status,s.email||s.id]);if(!r.rowCount)throw new HttpException('clause_not_found',404);return r.rows[0];});}

  @Post('rules/resolve')
  async rules(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.session(req);const asOf=date(body?.asOf);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const rows=(await c.query(`select id,rule_type,title,rule_text,status,source_locator,source_clause_id,precedence,valid_from effective_from,valid_to effective_to,metadata,case when metadata ? 'value' then metadata->'value' else to_jsonb(rule_text) end value from condo.rule where condominium_id=$1 and tenant_id=$2`,[condominiumId,s.organizationId])).rows;return resolveRuleSet(rows,asOf);});}

  @Post('ballots')
  async createBallot(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const eligible=Array.isArray(body?.eligibleSubjectHashes)?[...new Set(body.eligibleSubjectHashes.map(String).filter(Boolean))]:[];const quorum=body?.quorum||{};if(!body?.assemblyId||!body?.agendaItemId||!eligible.length)throw new HttpException('assemblyId, agendaItemId e eligibleSubjectHashes obrigatórios',400);const eligibility={subject_hashes:eligible,source:String(body?.eligibilitySource||'EXPLICIT_SNAPSHOT')};return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const own=await c.query(`select ai.id from condo.agenda_item ai join condo.assembly a on a.id=ai.assembly_id where ai.id=$1 and a.id=$2 and a.condominium_id=$3 and a.tenant_id=$4`,[body.agendaItemId,body.assemblyId,condominiumId,s.organizationId]);if(!own.rowCount)throw new HttpException('agenda_or_assembly_not_found',404);const r=await c.query(`insert into condo.ballot(tenant_id,condominium_id,assembly_id,agenda_item_id,status,eligibility_snapshot,eligibility_sha256,quorum_rule,opens_at,closes_at,created_by) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8::jsonb,$9,$10,$11) returning id,status,eligibility_sha256,quorum_rule,opens_at,closes_at,created_at`,[s.organizationId,condominiumId,body.assemblyId,body.agendaItemId,String(body?.status||'DRAFT').toUpperCase(),JSON.stringify(eligibility),hash(eligibility),JSON.stringify(quorum),body?.opensAt||null,body?.closesAt||null,s.email||s.id]);return r.rows[0];});}

  @Post('ballots/:ballotId/votes')
  async vote(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('ballotId') ballotId:string,@Body() body:any){const s=await this.session(req);const subjectHash=String(body?.voterSubjectHash||''),choice=String(body?.choice||'').toUpperCase(),signatureStatus=String(body?.signatureStatus||'PENDING').toUpperCase();if(!subjectHash||!['FOR','AGAINST','ABSTAIN'].includes(choice)||!['PENDING','VERIFIED','REJECTED'].includes(signatureStatus))throw new HttpException('vote inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const b=await c.query(`select id,status,eligibility_snapshot,opens_at,closes_at from condo.ballot where id=$1 and condominium_id=$2 and tenant_id=$3`,[ballotId,condominiumId,s.organizationId]);if(!b.rowCount)throw new HttpException('ballot_not_found',404);if(b.rows[0].status!=='OPEN')throw new HttpException('ballot_not_open',409);const eligible=new Set((b.rows[0].eligibility_snapshot?.subject_hashes||[]).map(String));if(!eligible.has(subjectHash))throw new HttpException('voter_not_in_eligibility_snapshot',403);try{return (await c.query(`insert into condo.ballot_vote(tenant_id,ballot_id,voter_subject_hash,choice,signature_status,signature_evidence) values($1,$2,$3,$4,$5,$6::jsonb) returning id,choice,signature_status,cast_at`,[s.organizationId,ballotId,subjectHash,choice,signatureStatus,JSON.stringify(body?.signatureEvidence||{})])).rows[0];}catch(e:any){if(String(e?.code)==='23505')throw new HttpException('duplicate_vote',409);throw e;}});}

  @Post('ballots/:ballotId/calculate')
  async calculate(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('ballotId') ballotId:string){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const b=await c.query(`select * from condo.ballot where id=$1 and condominium_id=$2 and tenant_id=$3`,[ballotId,condominiumId,s.organizationId]);if(!b.rowCount)throw new HttpException('ballot_not_found',404);const votes=(await c.query(`select voter_subject_hash subject_hash,choice,signature_status from condo.ballot_vote where ballot_id=$1 and tenant_id=$2 order by cast_at,id`,[ballotId,s.organizationId])).rows;const result=evaluateBallot({eligible_subject_hashes:b.rows[0].eligibility_snapshot?.subject_hashes||[],quorum:b.rows[0].quorum_rule,votes});if(result.status==='REQUIRES_INPUT')return result;await c.query(`update condo.ballot set status='CALCULATED',calculated_result=$3::jsonb where id=$1 and tenant_id=$2`,[ballotId,s.organizationId,JSON.stringify(result)]);return result;});}

  @Post('ballots/:ballotId/enact')
  async enact(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('ballotId') ballotId:string){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.ballot set status='ENACTED',enacted_by=$4,enacted_at=now() where id=$1 and condominium_id=$2 and tenant_id=$3 and status='CALCULATED' and coalesce((calculated_result->>'approved')::boolean,false)=true returning id,status,enacted_by,enacted_at,calculated_result`,[ballotId,condominiumId,s.organizationId,s.email||s.id]);if(!r.rowCount)throw new HttpException('ballot_not_calculated_or_not_approved',409);return r.rows[0];});}

  @Post('signatures')
  async signature(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const subjectType=String(body?.subjectType||'').toUpperCase();if(!['ASSEMBLY','DECISION','SANCTION','DOCUMENT'].includes(subjectType)||!body?.subjectId)throw new HttpException('subjectType/subjectId inválidos',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);return (await c.query(`insert into condo.signature_envelope(tenant_id,condominium_id,subject_type,subject_id,provider_code,provider_envelope_id,provider_secret_ref,status,evidence,completed_at,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) returning id,subject_type,subject_id,provider_code,provider_envelope_id,status,evidence,completed_at,created_at`,[s.organizationId,condominiumId,subjectType,body.subjectId,body?.providerCode||null,body?.providerEnvelopeId||null,body?.providerSecretRef||null,String(body?.status||'PENDING').toUpperCase(),JSON.stringify(body?.evidence||{}),body?.completedAt||null,s.email||s.id])).rows[0];});}

  @Post('sanctions')
  async sanction(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const ruleId=String(body?.sourceRuleId||''),kind=String(body?.kind||'').toUpperCase(),evidenceIds=Array.isArray(body?.evidenceIds)?body.evidenceIds.map(String):[];if(!ruleId||!['WARNING','FINE','OTHER'].includes(kind))throw new HttpException('sourceRuleId/kind inválidos',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const rule=await c.query(`select id,status from condo.rule where id=$1 and condominium_id=$2 and tenant_id=$3`,[ruleId,condominiumId,s.organizationId]);if(!rule.rowCount||rule.rows[0].status!=='CONFIRMED')throw new HttpException('confirmed_rule_required',409);if(!evidenceIds.length)throw new HttpException('evidenceIds obrigatório',409);const r=await c.query(`insert into condo.sanction_case(tenant_id,condominium_id,unit_id,occurrence_id,source_rule_id,status,proposed_kind,proposed_amount_cents,evidence_ids,notice_payload,defense_due_at,created_by) values($1,$2,$3,$4,$5,'NOTICE_PENDING',$6,$7,$8::uuid[],$9::jsonb,$10,$11) returning *`,[s.organizationId,condominiumId,body?.unitId||null,body?.occurrenceId||null,ruleId,kind,body?.proposedAmountCents??null,evidenceIds,JSON.stringify(body?.noticePayload||{}),body?.defenseDueAt||null,s.email||s.id]);return{...r.rows[0],guardrail:'No sanction is issued by this endpoint.'};});}

  @Post('sanctions/:sanctionId/defenses')
  async defense(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('sanctionId') sanctionId:string,@Body() body:any){const s=await this.session(req);const text=String(body?.text||'').trim();if(!text)throw new HttpException('text obrigatório',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const sc=await c.query(`select id from condo.sanction_case where id=$1 and condominium_id=$2 and tenant_id=$3 and status not in ('ISSUED','REJECTED','CANCELLED')`,[sanctionId,condominiumId,s.organizationId]);if(!sc.rowCount)throw new HttpException('sanction_not_open_for_defense',409);const r=await c.query(`insert into condo.defense(tenant_id,sanction_case_id,submitted_by,defense_text,evidence,status) values($1,$2,$3,$4,$5::jsonb,'SUBMITTED') returning id,status,created_at`,[s.organizationId,sanctionId,s.email||s.id,text,JSON.stringify(body?.evidence||{})]);await c.query(`update condo.sanction_case set status='DEFENSE_OPEN',updated_at=now() where id=$1`,[sanctionId]);return r.rows[0];});}

  @Post('sanctions/:sanctionId/review')
  async reviewSanction(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('sanctionId') sanctionId:string,@Body() body:any){const s=await this.manager(req);const decision=String(body?.decision||'').toUpperCase(),reason=String(body?.reason||'').trim();if(!['APPROVE','REJECT'].includes(decision)||!reason)throw new HttpException('decision/reason obrigatórios',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const sc=await c.query(`select s.*,r.status rule_status from condo.sanction_case s join condo.rule r on r.id=s.source_rule_id where s.id=$1 and s.condominium_id=$2 and s.tenant_id=$3`,[sanctionId,condominiumId,s.organizationId]);if(!sc.rowCount)throw new HttpException('sanction_not_found',404);const d=await c.query(`select status from condo.defense where sanction_case_id=$1 and tenant_id=$2 order by created_at desc limit 1`,[sanctionId,s.organizationId]);const defenseStatus=d.rows[0]?.status||null;const guard=sanctionGuard({rule_status:sc.rows[0].rule_status,evidence_ids:sc.rows[0].evidence_ids,human_decision:decision,human_reviewer:s.email||s.id,decision_reason:reason,defense_status:defenseStatus});if(guard.status==='DEFENSE_DUE_PROCESS_REQUIRED')return guard;const next=decision==='APPROVE'?'READY_FOR_MANUAL_ISSUANCE':'REJECTED';const r=await c.query(`update condo.sanction_case set status=$4,human_decision=$5,human_decision_by=$6,human_decision_reason=$7,human_decision_at=now(),updated_at=now() where id=$1 and condominium_id=$2 and tenant_id=$3 returning *`,[sanctionId,condominiumId,s.organizationId,next,decision,s.email||s.id,reason]);return{...r.rows[0],guard};});}

  @Post('sanctions/:sanctionId/issue')
  async issue(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('sanctionId') sanctionId:string){const s=await this.manager(req);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.sanction_case set status='ISSUED',issued_by=$4,issued_at=now(),updated_at=now() where id=$1 and condominium_id=$2 and tenant_id=$3 and status='READY_FOR_MANUAL_ISSUANCE' and human_decision='APPROVE' returning *`,[sanctionId,condominiumId,s.organizationId,s.email||s.id]);if(!r.rowCount)throw new HttpException('sanction_not_ready_for_manual_issuance',409);return r.rows[0];});}

  @Post('sanctions/:sanctionId/charges')
  async charge(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('sanctionId') sanctionId:string,@Body() body:any){const s=await this.manager(req);const amount=Number(body?.amountCents);if(!Number.isInteger(amount)||amount<0)throw new HttpException('amountCents inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const sc=await c.query(`select id,unit_id from condo.sanction_case where id=$1 and condominium_id=$2 and tenant_id=$3 and status='ISSUED'`,[sanctionId,condominiumId,s.organizationId]);if(!sc.rowCount)throw new HttpException('issued_sanction_required',409);return (await c.query(`insert into condo.charge(tenant_id,condominium_id,unit_id,sanction_case_id,amount_cents,due_date,status,evidence,created_by) values($1,$2,$3,$4,$5,$6,'READY_FOR_BILLING',$7::jsonb,$8) returning *`,[s.organizationId,condominiumId,sc.rows[0].unit_id,sanctionId,amount,body?.dueDate||null,JSON.stringify(body?.evidence||{}),s.email||s.id])).rows[0];});}

  @Post('communications/endpoints')
  async endpoint(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const provider=String(body?.providerCode||'').trim(),channel=String(body?.channel||'').toUpperCase();if(!provider||!['EMAIL','SMS','WHATSAPP','PUSH','ADMIN_API','OTHER'].includes(channel))throw new HttpException('providerCode/channel inválidos',400);if(body?.secret&&!body?.secretRef)throw new HttpException('store_secret_by_reference_only',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);return (await c.query(`insert into condo.communication_endpoint(tenant_id,condominium_id,provider_code,channel,endpoint_ref,secret_ref,status,metadata) values($1,$2,$3,$4,$5,$6,'CONFIGURED',$7::jsonb) on conflict(tenant_id,condominium_id,provider_code,channel) do update set endpoint_ref=excluded.endpoint_ref,secret_ref=excluded.secret_ref,status='CONFIGURED',metadata=excluded.metadata,updated_at=now() returning id,provider_code,channel,endpoint_ref,secret_ref,status,metadata`,[s.organizationId,condominiumId,provider,channel,body?.endpointRef||null,body?.secretRef||null,JSON.stringify(body?.metadata||{})])).rows[0];});}

  @Post('legal-monitors')
  async monitor(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const sourceCode=String(body?.sourceCode||'').trim();if(!sourceCode)throw new HttpException('sourceCode obrigatório',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);return (await c.query(`insert into condo.legal_monitor(tenant_id,condominium_id,source_code,status,configuration,last_snapshot_id) values($1,$2,$3,'ACTIVE',$4::jsonb,$5) on conflict(tenant_id,condominium_id,source_code) do update set status='ACTIVE',configuration=excluded.configuration,last_snapshot_id=coalesce(excluded.last_snapshot_id,condo.legal_monitor.last_snapshot_id) returning *`,[s.organizationId,condominiumId,sourceCode,JSON.stringify(body?.configuration||{}),body?.lastSnapshotId||null])).rows[0];});}

  @Post('legal-monitors/:monitorId/check')
  async checkMonitor(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('monitorId') monitorId:string,@Body() body:any){const s=await this.manager(req);const before=Array.isArray(body?.beforeRules)?body.beforeRules:[],after=Array.isArray(body?.afterRules)?body.afterRules:[],afterSnapshot=String(body?.afterSnapshotId||'');if(!afterSnapshot)throw new HttpException('afterSnapshotId obrigatório',400);const diff=legalChangeDiff(before,after);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const m=await c.query(`select id,last_snapshot_id from condo.legal_monitor where id=$1 and condominium_id=$2 and tenant_id=$3 and status='ACTIVE'`,[monitorId,condominiumId,s.organizationId]);if(!m.rowCount)throw new HttpException('active_monitor_not_found',404);let eventId=null;if(diff.events.length){const e=await c.query(`insert into condo.legal_monitor_event(tenant_id,monitor_id,before_snapshot_id,after_snapshot_id,status,change_summary) values($1,$2,$3,$4,'CANDIDATE_REVIEW',$5::jsonb) returning id`,[s.organizationId,monitorId,m.rows[0].last_snapshot_id||body?.beforeSnapshotId||null,afterSnapshot,JSON.stringify(diff)]);eventId=e.rows[0].id;}await c.query(`update condo.legal_monitor set last_snapshot_id=$3,last_checked_at=now() where id=$1 and tenant_id=$2`,[monitorId,s.organizationId,afterSnapshot]);return{...diff,eventId,legalChangeConfirmed:false};});}

  @Post('integrations')
  async integration(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const targetType=String(body?.targetType||'').toUpperCase(),targetId=String(body?.targetId||'');if(!['PROPERTY','AITEC_PROJECT'].includes(targetType)||!targetId)throw new HttpException('targetType/targetId inválidos',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);if(targetType==='PROPERTY'){const t=await c.query(`select id from property360.property where id=$1 and tenant_id=$2`,[targetId,s.organizationId]);if(!t.rowCount)throw new HttpException('property_not_found',404);}else{const t=await c.query(`select id from aitec.project where id=$1 and tenant_id=$2`,[targetId,s.organizationId]);if(!t.rowCount)throw new HttpException('aitec_project_not_found',404);}return (await c.query(`insert into condo.integration_link(tenant_id,condominium_id,target_type,target_id,status,metadata) values($1,$2,$3,$4,'ACTIVE',$5::jsonb) on conflict(tenant_id,condominium_id,target_type,target_id) do update set status='ACTIVE',metadata=excluded.metadata returning *`,[s.organizationId,condominiumId,targetType,targetId,JSON.stringify(body?.metadata||{})])).rows[0];});}

  @Get('external-summary')
  async summary(@Req() req:any,@Param('condominiumId') condominiumId:string,@Query('mode') mode='BUYER'){const s=await this.session(req);return tenantTx(pool,s.organizationId,async c=>{const condominium=await this.own(c,condominiumId,s.organizationId);const rules=(await c.query(`select id,rule_type parameter,rule_text value,source_locator,status,array_remove(array_agg(el.id),null) evidence_ids from condo.rule r left join condo.evidence_link el on el.rule_id=r.id where r.condominium_id=$1 and r.tenant_id=$2 group by r.id order by r.created_at desc`,[condominiumId,s.organizationId])).rows;const links=(await c.query(`select target_type,target_id from condo.integration_link where condominium_id=$1 and tenant_id=$2 and status='ACTIVE'`,[condominiumId,s.organizationId])).rows;return buildExternalSummary({mode,condominium,rules,property_id:links.find((x:any)=>x.target_type==='PROPERTY')?.target_id,aitec_project_id:links.find((x:any)=>x.target_type==='AITEC_PROJECT')?.target_id});});}

  @Post('retrieval-acl')
  async acl(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const documentId=String(body?.documentId||''),subjectType=String(body?.subjectType||'').toUpperCase(),subjectRef=String(body?.subjectRef||'');if(!documentId||!['ROLE','USER','EXTERNAL_MODE'].includes(subjectType)||!subjectRef)throw new HttpException('documentId/subjectType/subjectRef inválidos',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const d=await c.query(`select id from condo.document where id=$1 and condominium_id=$2 and tenant_id=$3`,[documentId,condominiumId,s.organizationId]);if(!d.rowCount)throw new HttpException('document_not_found',404);return (await c.query(`insert into condo.retrieval_acl(tenant_id,condominium_id,document_id,subject_type,subject_ref,permission,valid_from,valid_to) values($1,$2,$3,$4,$5,'READ',$6,$7) on conflict(tenant_id,document_id,subject_type,subject_ref) do update set valid_from=excluded.valid_from,valid_to=excluded.valid_to returning *`,[s.organizationId,condominiumId,documentId,subjectType,subjectRef,body?.validFrom||null,body?.validTo||null])).rows[0];});}

  @Post('retrieve')
  async retrieve(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.session(req);const question=String(body?.query||'').trim();if(!question)throw new HttpException('query obrigatório',400);const baseDate=date(body?.baseDate);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const roles=Array.isArray(s.roles)?s.roles.map(String):[];const userRefs=[String(s.id||''),String(s.email||'')].filter(Boolean);const docs=(await c.query(`select distinct document_id from condo.retrieval_acl where tenant_id=$1 and condominium_id=$2 and permission='READ' and (valid_from is null or valid_from<=now()) and (valid_to is null or valid_to>now()) and ((subject_type='ROLE' and subject_ref=any($3::text[])) or (subject_type='USER' and subject_ref=any($4::text[])))`,[s.organizationId,condominiumId,roles,userRefs])).rows.map((x:any)=>String(x.document_id));const acl=buildRetrievalAcl(s.organizationId,condominiumId,docs);if(!docs.length)return{status:'NO_AUTHORIZED_DOCUMENTS',acl,evidence:[],policy:'Empty ACL is resolved before retrieval and never falls back to tenant-wide search.'};const url=String(process.env.AI_GATEWAY_INTERNAL_URL||'http://ai-gateway:3003').replace(/\/$/,'')+'/ai/v1/retrieve';const token=process.env.INTERNAL_API_TOKEN||'';if(!token)throw new HttpException('internal_ai_not_configured',503);const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-internal-token':token},body:JSON.stringify({tenantId:s.organizationId,query:question,scope:{domains:['condo'],documentIds:docs,includePublic:false,baseDate,knowledgeStatuses:['CONFIRMED'],visibility:['PRIVATE','TENANT']}})});const payload:any=await r.json().catch(()=>({}));if(!r.ok)throw new HttpException(`ai_retrieval_failed:${r.status}`,502);return{status:'OK',acl:{...acl,document_ids:docs},retrieval:payload,policy:'Document ACL is resolved in PostgreSQL before AI retrieval; documentIds are passed as an OpenSearch filter.'};});}
}
