import {Body,Controller,HttpException,Param,Post,Req} from '@nestjs/common';
import {createHash} from 'crypto';
import {Pool} from 'pg';
import {AuthService} from '../auth.service';
import {tenantTx} from '../common/tenant-db';

const pool=new Pool({connectionString:process.env.PLATFORM_DATABASE_URL});
@Controller('api/v1/condominiums/:condominiumId/v20')
export class CondoV20OpsController{
  constructor(private readonly auth:AuthService){}
  private async manager(req:any){const s=await this.auth.get(req.cookies?.ld_session);if(!s?.organizationId)throw new HttpException('unauthorized',401);const modules=Array.isArray(s.entitlements?.modules)?s.entitlements.modules:[];if(!s.roles?.includes('admin')&&!modules.includes('condominio'))throw new HttpException('module_not_entitled',403);if(!s.roles?.some((r:string)=>r==='admin'||r==='condo_manager'))throw new HttpException('forbidden',403);return s;}
  private async own(c:any,id:string,tenant:string){const r=await c.query(`select id from condo.condominium where id=$1 and tenant_id=$2`,[id,tenant]);if(!r.rowCount)throw new HttpException('condominium_not_found',404);}

  @Post('defenses/:defenseId/review')
  async reviewDefense(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('defenseId') defenseId:string,@Body() body:any){const s=await this.manager(req);const resolution=String(body?.resolution||'').trim();if(!resolution)throw new HttpException('resolution obrigatório',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const d=await c.query(`select d.id,d.sanction_case_id from condo.defense d join condo.sanction_case sc on sc.id=d.sanction_case_id where d.id=$1 and sc.condominium_id=$2 and d.tenant_id=$3`,[defenseId,condominiumId,s.organizationId]);if(!d.rowCount)throw new HttpException('defense_not_found',404);const r=await c.query(`update condo.defense set status='RESOLVED',resolution=$4,reviewed_by=$5,reviewed_at=now() where id=$1 and tenant_id=$2 returning id,sanction_case_id,status,resolution,reviewed_by,reviewed_at`,[defenseId,s.organizationId,condominiumId,resolution,s.email||s.id]);await c.query(`update condo.sanction_case set status='UNDER_HUMAN_REVIEW',updated_at=now() where id=$1 and tenant_id=$2 and status='DEFENSE_OPEN'`,[d.rows[0].sanction_case_id,s.organizationId]);return r.rows[0];});}

  @Post('signatures/:envelopeId/status')
  async signatureStatus(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('envelopeId') envelopeId:string,@Body() body:any){const s=await this.manager(req);const status=String(body?.status||'').toUpperCase();if(!['SENT','PARTIALLY_SIGNED','SIGNED','REJECTED','EXPIRED','CANCELLED'].includes(status))throw new HttpException('status inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.signature_envelope set status=$4,evidence=evidence||$5::jsonb,completed_at=case when $4 in ('SIGNED','REJECTED','EXPIRED','CANCELLED') then now() else completed_at end where id=$1 and condominium_id=$2 and tenant_id=$3 returning id,subject_type,subject_id,provider_code,provider_envelope_id,status,evidence,completed_at`,[envelopeId,condominiumId,s.organizationId,status,JSON.stringify(body?.evidence||{})]);if(!r.rowCount)throw new HttpException('signature_envelope_not_found',404);return r.rows[0];});}

  @Post('communications/send')
  async send(@Req() req:any,@Param('condominiumId') condominiumId:string,@Body() body:any){const s=await this.manager(req);const endpointId=String(body?.endpointId||''),recipientRef=String(body?.recipientRef||''),templateCode=String(body?.templateCode||'').trim();if(!endpointId||!recipientRef||!templateCode)throw new HttpException('endpointId/recipientRef/templateCode obrigatórios',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const e=await c.query(`select id,provider_code,channel,endpoint_ref,secret_ref,status from condo.communication_endpoint where id=$1 and condominium_id=$2 and tenant_id=$3 and status='CONFIGURED'`,[endpointId,condominiumId,s.organizationId]);if(!e.rowCount)throw new HttpException('communication_endpoint_not_configured',409);const payload=body?.payload||{};const recipientHash=createHash('sha256').update(recipientRef).digest('hex'),payloadHash=createHash('sha256').update(JSON.stringify(payload)).digest('hex');const r=await c.query(`insert into condo.communication_log(tenant_id,condominium_id,endpoint_id,subject_type,subject_id,recipient_ref_hash,template_code,status,payload_sha256) values($1,$2,$3,$4,$5,$6,$7,'QUEUED',$8) returning id,status,recipient_ref_hash,template_code,payload_sha256,created_at`,[s.organizationId,condominiumId,endpointId,body?.subjectType||null,body?.subjectId||null,recipientHash,templateCode,payloadHash]);return{...r.rows[0],dispatch:{provider:e.rows[0].provider_code,channel:e.rows[0].channel,endpointRef:e.rows[0].endpoint_ref,secretRef:e.rows[0].secret_ref,payload},policy:'This endpoint queues an auditable dispatch contract; provider transport is an external integration and secrets are referenced, never returned.'};});}

  @Post('communications/:logId/result')
  async communicationResult(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('logId') logId:string,@Body() body:any){const s=await this.manager(req);const status=String(body?.status||'').toUpperCase();if(!['SENT','DELIVERED','FAILED','CANCELLED'].includes(status))throw new HttpException('status inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.communication_log set status=$4,provider_message_id=$5,error=$6,completed_at=case when $4 in ('DELIVERED','FAILED','CANCELLED') then now() else completed_at end where id=$1 and condominium_id=$2 and tenant_id=$3 returning id,status,provider_message_id,error,completed_at`,[logId,condominiumId,s.organizationId,status,body?.providerMessageId||null,body?.error||null]);if(!r.rowCount)throw new HttpException('communication_log_not_found',404);return r.rows[0];});}

  @Post('legal-monitor-events/:eventId/review')
  async reviewMonitorEvent(@Req() req:any,@Param('condominiumId') condominiumId:string,@Param('eventId') eventId:string,@Body() body:any){const s=await this.manager(req);const status=String(body?.status||'').toUpperCase();if(!['CONFIRMED','REJECTED'].includes(status))throw new HttpException('status inválido',400);return tenantTx(pool,s.organizationId,async c=>{await this.own(c,condominiumId,s.organizationId);const r=await c.query(`update condo.legal_monitor_event e set status=$5,reviewed_by=$6,reviewed_at=now() from condo.legal_monitor m where e.id=$1 and e.monitor_id=m.id and m.condominium_id=$2 and e.tenant_id=$3 and m.tenant_id=$4 returning e.id,e.status,e.change_summary,e.reviewed_by,e.reviewed_at`,[eventId,condominiumId,s.organizationId,s.organizationId,status,s.email||s.id]);if(!r.rowCount)throw new HttpException('legal_monitor_event_not_found',404);return r.rows[0];});}
}
